import type {
  CoverageDietaryProfile,
  CoverageDishType,
  CoverageEquipmentProfile,
  CoverageMealType,
  CoveragePriority,
} from '../domain/recipe-coverage.policy';
import { suggestDesiredCount } from '../domain/recipe-coverage.policy';

export type CoverageSlotSeed = {
  name: string;
  description: string;
  mealType: CoverageMealType;
  /** Resolved at seed time via Product.productKey */
  primaryProductKey: string | null;
  dishType: CoverageDishType;
  cookingMethod: string | null;
  calorieMin: number | null;
  calorieMax: number | null;
  proteinMin: number | null;
  fatMax: number | null;
  maximumTimeMinutes: number | null;
  maximumCost: number | null;
  currency: string | null;
  dietaryProfile: CoverageDietaryProfile;
  equipmentProfile: CoverageEquipmentProfile;
  priority: CoveragePriority;
  desiredRecipeCount?: number;
  sortRank: number;
  provenance: string;
  rationale: string;
};

function s(
  partial: Omit<CoverageSlotSeed, 'desiredRecipeCount' | 'currency' | 'maximumCost'> & {
    desiredRecipeCount?: number;
    maximumCost?: number | null;
    currency?: string | null;
  },
): CoverageSlotSeed {
  return {
    desiredRecipeCount: partial.desiredRecipeCount ?? suggestDesiredCount(partial.priority),
    maximumCost: partial.maximumCost ?? null,
    currency: partial.currency ?? (partial.maximumCost != null ? 'RUB' : null),
    ...partial,
  };
}

/**
 * coverage-core-v1 — curated 50–80 slots (no Cartesian explosion).
 * Focus: chicken, buckwheat, cottage cheese, eggs, pollock + cross-product basics.
 */
export const COVERAGE_CORE_V1_SLOTS: CoverageSlotSeed[] = [
  // —— Chicken wave ——
  s({
    name: 'Lunch chicken MAIN stove',
    description: 'Обед с куриным филе как основным белком',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 300,
    calorieMax: 650,
    proteinMin: 25,
    fatMax: 25,
    maximumTimeMinutes: 45,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'CRITICAL',
    sortRank: 10,
    provenance: 'WAVE1_CHICKEN',
    rationale: 'Ключевой белок первой волны; высокая частота в Meal Plan',
  }),
  s({
    name: 'Dinner chicken MAIN bake',
    description: 'Ужин с запечённой курицей',
    mealType: 'dinner',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'BAKE',
    calorieMin: 280,
    calorieMax: 600,
    proteinMin: 25,
    fatMax: 22,
    maximumTimeMinutes: 60,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'OVEN',
    priority: 'CRITICAL',
    sortRank: 20,
    provenance: 'WAVE1_CHICKEN',
    rationale: 'Вечерний основной белок; oven — распространённое оборудование',
  }),
  s({
    name: 'Lunch chicken BOWL grill',
    description: 'Обед-боул с курицей на гриле/сковороде',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'BOWL',
    cookingMethod: 'GRILL',
    calorieMin: 350,
    calorieMax: 700,
    proteinMin: 28,
    fatMax: 24,
    maximumTimeMinutes: 40,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 30,
    provenance: 'WAVE1_CHICKEN',
    rationale: 'Высокобелковый боул для обеда',
  }),
  s({
    name: 'Dinner chicken MAIN boil',
    description: 'Ужин с отварной курицей',
    mealType: 'dinner',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'BOIL',
    calorieMin: 250,
    calorieMax: 550,
    proteinMin: 28,
    fatMax: 18,
    maximumTimeMinutes: 50,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 40,
    provenance: 'WAVE1_CHICKEN',
    rationale: 'Низкожирный вариант курицы',
  }),
  s({
    name: 'Lunch chicken MAIN stew budget',
    description: 'Бюджетный тушёный обед с курицей',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'STEW',
    calorieMin: 300,
    calorieMax: 600,
    proteinMin: 22,
    fatMax: 22,
    maximumTimeMinutes: 55,
    maximumCost: 180,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 50,
    provenance: 'WAVE1_CHICKEN_BUDGET',
    rationale: 'Бюджетный слот первой волны',
  }),
  s({
    name: 'Dinner chicken MAIN quick',
    description: 'Быстрый ужин с курицей ≤25 мин',
    mealType: 'dinner',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 280,
    calorieMax: 580,
    proteinMin: 24,
    fatMax: 24,
    maximumTimeMinutes: 25,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'CRITICAL',
    sortRank: 60,
    provenance: 'WAVE1_CHICKEN_QUICK',
    rationale: 'Быстрые блюда критичны для adherence',
  }),

  // —— Buckwheat ——
  s({
    name: 'Lunch buckwheat SIDE boil',
    description: 'Гречка как гарнир на обед',
    mealType: 'lunch',
    primaryProductKey: 'step093_buckwheat',
    dishType: 'SIDE',
    cookingMethod: 'BOIL',
    calorieMin: 150,
    calorieMax: 400,
    proteinMin: 5,
    fatMax: 12,
    maximumTimeMinutes: 35,
    dietaryProfile: 'VEGAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'CRITICAL',
    sortRank: 70,
    provenance: 'WAVE1_BUCKWHEAT',
    rationale: 'Базовый крахмал первой волны',
  }),
  s({
    name: 'Dinner buckwheat PORRIDGE',
    description: 'Гречневая каша на ужин',
    mealType: 'dinner',
    primaryProductKey: 'buckwheat_boiled',
    dishType: 'PORRIDGE',
    cookingMethod: 'BOIL',
    calorieMin: 180,
    calorieMax: 450,
    proteinMin: 6,
    fatMax: 14,
    maximumTimeMinutes: 40,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 80,
    provenance: 'WAVE1_BUCKWHEAT',
    rationale: 'Каша как отдельный слот, не дубль MAIN',
  }),
  s({
    name: 'Breakfast buckwheat PORRIDGE',
    description: 'Гречка на завтрак',
    mealType: 'breakfast',
    primaryProductKey: 'buckwheat_flakes_dry',
    dishType: 'PORRIDGE',
    cookingMethod: 'BOIL',
    calorieMin: 200,
    calorieMax: 450,
    proteinMin: 7,
    fatMax: 12,
    maximumTimeMinutes: 25,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 90,
    provenance: 'WAVE1_BUCKWHEAT',
    rationale: 'Утренний крахмальный слот',
  }),
  s({
    name: 'Lunch chicken+buckwheat MAIN',
    description: 'Обед курица с гречкой (семейный паттерн)',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 350,
    calorieMax: 700,
    proteinMin: 28,
    fatMax: 24,
    maximumTimeMinutes: 45,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'CRITICAL',
    desiredRecipeCount: 3,
    sortRank: 100,
    provenance: 'WAVE1_CHICKEN_BUCKWHEAT',
    rationale: 'Детерминированное семейство chicken-with-side',
  }),

  // —— Cottage cheese ——
  s({
    name: 'Breakfast cottage SNACK',
    description: 'Творожный завтрак/перекус',
    mealType: 'breakfast',
    primaryProductKey: 'cottage_cheese_5pct',
    dishType: 'BREAKFAST',
    cookingMethod: 'RAW',
    calorieMin: 150,
    calorieMax: 400,
    proteinMin: 18,
    fatMax: 12,
    maximumTimeMinutes: 10,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'CRITICAL',
    sortRank: 110,
    provenance: 'WAVE1_COTTAGE',
    rationale: 'Быстрый белковый завтрак без оборудования',
  }),
  s({
    name: 'Snack cottage SNACK',
    description: 'Творожный перекус',
    mealType: 'snack',
    primaryProductKey: 'cottage_cheese_5pct',
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 120,
    calorieMax: 350,
    proteinMin: 15,
    fatMax: 10,
    maximumTimeMinutes: 10,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'HIGH',
    sortRank: 120,
    provenance: 'WAVE1_COTTAGE',
    rationale: 'Перекус с контролируемым белком',
  }),
  s({
    name: 'Afternoon cottage SNACK lactose-free band',
    description: 'Послеобеденный творожный слот (общий профиль)',
    mealType: 'afternoon_snack',
    primaryProductKey: 'cottage_cheese_0pct',
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 100,
    calorieMax: 300,
    proteinMin: 15,
    fatMax: 5,
    maximumTimeMinutes: 10,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'MEDIUM',
    sortRank: 130,
    provenance: 'WAVE1_COTTAGE',
    rationale: 'Низкожирный творог 0%',
  }),

  // —— Eggs ——
  s({
    name: 'Breakfast eggs BREAKFAST fry',
    description: 'Яичница / scramble на завтрак',
    mealType: 'breakfast',
    primaryProductKey: 'eggs',
    dishType: 'BREAKFAST',
    cookingMethod: 'FRY',
    calorieMin: 200,
    calorieMax: 450,
    proteinMin: 14,
    fatMax: 28,
    maximumTimeMinutes: 15,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'CRITICAL',
    sortRank: 140,
    provenance: 'WAVE1_EGGS',
    rationale: 'Базовый яичный завтрак',
  }),
  s({
    name: 'Breakfast eggs boil',
    description: 'Варёные яйца на завтрак',
    mealType: 'breakfast',
    primaryProductKey: 'egg_boiled',
    dishType: 'BREAKFAST',
    cookingMethod: 'BOIL',
    calorieMin: 140,
    calorieMax: 350,
    proteinMin: 12,
    fatMax: 18,
    maximumTimeMinutes: 15,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 150,
    provenance: 'WAVE1_EGGS',
    rationale: 'Простой и предсказуемый завтрак',
  }),
  s({
    name: 'Snack eggs SNACK',
    description: 'Яичный перекус',
    mealType: 'snack',
    primaryProductKey: 'eggs',
    dishType: 'SNACK',
    cookingMethod: 'BOIL',
    calorieMin: 100,
    calorieMax: 280,
    proteinMin: 10,
    fatMax: 16,
    maximumTimeMinutes: 15,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 160,
    provenance: 'WAVE1_EGGS',
    rationale: 'Белковый snack без сложного оборудования',
  }),

  // —— Pollock ——
  s({
    name: 'Dinner pollock MAIN bake',
    description: 'Ужин с запечённым минтаем',
    mealType: 'dinner',
    primaryProductKey: 'pollock_raw',
    dishType: 'MAIN',
    cookingMethod: 'BAKE',
    calorieMin: 220,
    calorieMax: 520,
    proteinMin: 24,
    fatMax: 16,
    maximumTimeMinutes: 45,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'OVEN',
    priority: 'CRITICAL',
    sortRank: 170,
    provenance: 'WAVE1_POLLOCK',
    rationale: 'Рыбный белок первой волны',
  }),
  s({
    name: 'Lunch pollock MAIN boil',
    description: 'Обед с отварным минтаем',
    mealType: 'lunch',
    primaryProductKey: 'pollock_boiled',
    dishType: 'MAIN',
    cookingMethod: 'BOIL',
    calorieMin: 200,
    calorieMax: 480,
    proteinMin: 24,
    fatMax: 12,
    maximumTimeMinutes: 40,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 180,
    provenance: 'WAVE1_POLLOCK',
    rationale: 'Низкожирный рыбный обед',
  }),
  s({
    name: 'Dinner pollock MAIN stew budget',
    description: 'Бюджетный ужин с минтаем',
    mealType: 'dinner',
    primaryProductKey: 'pollock_raw',
    dishType: 'MAIN',
    cookingMethod: 'STEW',
    calorieMin: 220,
    calorieMax: 520,
    proteinMin: 22,
    fatMax: 18,
    maximumTimeMinutes: 50,
    maximumCost: 160,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 190,
    provenance: 'WAVE1_POLLOCK_BUDGET',
    rationale: 'Доступная рыба для вечернего плана',
  }),

  // —— Cross-product meal structure ——
  s({
    name: 'Breakfast GENERAL porridge',
    description: 'Базовая каша на завтрак без фиксированного Product',
    mealType: 'breakfast',
    primaryProductKey: null,
    dishType: 'PORRIDGE',
    cookingMethod: 'BOIL',
    calorieMin: 200,
    calorieMax: 450,
    proteinMin: 6,
    fatMax: 14,
    maximumTimeMinutes: 25,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'CRITICAL',
    sortRank: 200,
    provenance: 'CROSS_BREAKFAST',
    rationale: 'Структурный слот завтрака',
  }),
  s({
    name: 'Breakfast GENERAL yogurt snack',
    description: 'Йогуртовый/молочный завтрак-перекус',
    mealType: 'breakfast',
    primaryProductKey: null,
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 120,
    calorieMax: 350,
    proteinMin: 10,
    fatMax: 12,
    maximumTimeMinutes: 5,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'HIGH',
    sortRank: 210,
    provenance: 'CROSS_BREAKFAST',
    rationale: 'Быстрый завтрак без плиты',
  }),
  s({
    name: 'Lunch GENERAL soup',
    description: 'Обеденный суп',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'SOUP',
    cookingMethod: 'BOIL',
    calorieMin: 150,
    calorieMax: 450,
    proteinMin: 8,
    fatMax: 18,
    maximumTimeMinutes: 50,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 220,
    provenance: 'CROSS_LUNCH',
    rationale: 'Супы как отдельный dishType',
  }),
  s({
    name: 'Lunch GENERAL salad',
    description: 'Обеденный салат',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'SALAD',
    cookingMethod: 'RAW',
    calorieMin: 120,
    calorieMax: 400,
    proteinMin: 6,
    fatMax: 22,
    maximumTimeMinutes: 20,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'MEDIUM',
    sortRank: 230,
    provenance: 'CROSS_LUNCH',
    rationale: 'Лёгкий обеденный слот',
  }),
  s({
    name: 'Dinner GENERAL MAIN stove',
    description: 'Универсальный ужин MAIN на плите',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 300,
    calorieMax: 650,
    proteinMin: 20,
    fatMax: 25,
    maximumTimeMinutes: 40,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 240,
    provenance: 'CROSS_DINNER',
    rationale: 'Широкий ужин без жёсткого Product',
  }),
  s({
    name: 'Dinner GENERAL quick no special gear',
    description: 'Быстрый ужин без спец. оборудования',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: null,
    calorieMin: 280,
    calorieMax: 600,
    proteinMin: 18,
    fatMax: 24,
    maximumTimeMinutes: 25,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'CRITICAL',
    sortRank: 250,
    provenance: 'CROSS_QUICK',
    rationale: 'Quick + no special equipment',
  }),
  s({
    name: 'Snack GENERAL budget',
    description: 'Бюджетный перекус',
    mealType: 'snack',
    primaryProductKey: null,
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 80,
    calorieMax: 250,
    proteinMin: 5,
    fatMax: 12,
    maximumTimeMinutes: 10,
    maximumCost: 80,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'MEDIUM',
    sortRank: 260,
    provenance: 'CROSS_BUDGET',
    rationale: 'Низкая стоимость перекуса',
  }),
  s({
    name: 'Afternoon snack GENERAL',
    description: 'Послеобеденный перекус',
    mealType: 'afternoon_snack',
    primaryProductKey: null,
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 80,
    calorieMax: 280,
    proteinMin: 6,
    fatMax: 12,
    maximumTimeMinutes: 10,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'MEDIUM',
    sortRank: 270,
    provenance: 'CROSS_SNACK',
    rationale: 'Структурный afternoon_snack',
  }),

  // —— Dietary variants ——
  s({
    name: 'Lunch vegetarian MAIN',
    description: 'Вегетарианский обед MAIN',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'STEW',
    calorieMin: 300,
    calorieMax: 600,
    proteinMin: 12,
    fatMax: 22,
    maximumTimeMinutes: 45,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 280,
    provenance: 'DIET_VEGETARIAN',
    rationale: 'Покрытие VEGETARIAN без UNKNOWN composition',
  }),
  s({
    name: 'Dinner vegan MAIN',
    description: 'Веганский ужин',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'BOIL',
    calorieMin: 280,
    calorieMax: 580,
    proteinMin: 12,
    fatMax: 20,
    maximumTimeMinutes: 45,
    dietaryProfile: 'VEGAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 290,
    provenance: 'DIET_VEGAN',
    rationale: 'Базовый vegan MAIN',
  }),
  s({
    name: 'Lunch gluten-free MAIN chicken',
    description: 'Безглютеновый обед с курицей',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'BAKE',
    calorieMin: 300,
    calorieMax: 620,
    proteinMin: 26,
    fatMax: 22,
    maximumTimeMinutes: 50,
    dietaryProfile: 'GLUTEN_FREE',
    equipmentProfile: 'OVEN',
    priority: 'MEDIUM',
    sortRank: 300,
    provenance: 'DIET_GF',
    rationale: 'GF + ключевой белок',
  }),
  s({
    name: 'Breakfast lactose-free',
    description: 'Завтрак без лактозы',
    mealType: 'breakfast',
    primaryProductKey: null,
    dishType: 'BREAKFAST',
    cookingMethod: 'BOIL',
    calorieMin: 180,
    calorieMax: 420,
    proteinMin: 8,
    fatMax: 14,
    maximumTimeMinutes: 25,
    dietaryProfile: 'LACTOSE_FREE',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 310,
    provenance: 'DIET_LF',
    rationale: 'LACTOSE_FREE structural slot',
  }),
  s({
    name: 'Dinner high-protein MAIN',
    description: 'Высокобелковый ужин',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'GRILL',
    calorieMin: 320,
    calorieMax: 650,
    proteinMin: 35,
    fatMax: 22,
    maximumTimeMinutes: 40,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 320,
    provenance: 'DIET_HP',
    rationale: 'HIGH_PROTEIN evening slot',
  }),

  // —— Equipment / method diversity ——
  s({
    name: 'Lunch multicooker MAIN',
    description: 'Обед в мультиварке',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'STEW',
    calorieMin: 300,
    calorieMax: 620,
    proteinMin: 18,
    fatMax: 22,
    maximumTimeMinutes: 60,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'MULTICOOKER',
    priority: 'LOW',
    sortRank: 330,
    provenance: 'EQUIP_MULTICOOKER',
    rationale: 'Опциональное оборудование — LOW priority',
  }),
  s({
    name: 'Breakfast blender smoothie-like',
    description: 'Завтрак с блендером',
    mealType: 'breakfast',
    primaryProductKey: null,
    dishType: 'SNACK',
    cookingMethod: 'BLEND',
    calorieMin: 150,
    calorieMax: 400,
    proteinMin: 10,
    fatMax: 14,
    maximumTimeMinutes: 15,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BLENDER',
    priority: 'LOW',
    sortRank: 340,
    provenance: 'EQUIP_BLENDER',
    rationale: 'Не обязателен для первой волны',
  }),
  s({
    name: 'Dinner grill MAIN chicken',
    description: 'Ужин курица на гриле',
    mealType: 'dinner',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'GRILL',
    calorieMin: 280,
    calorieMax: 580,
    proteinMin: 28,
    fatMax: 20,
    maximumTimeMinutes: 35,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'GRILL',
    priority: 'MEDIUM',
    sortRank: 350,
    provenance: 'EQUIP_GRILL',
    rationale: 'Гриль-вариант курицы',
  }),
  s({
    name: 'Lunch steam MAIN fish',
    description: 'Обед на пару с рыбой',
    mealType: 'lunch',
    primaryProductKey: 'pollock_raw',
    dishType: 'MAIN',
    cookingMethod: 'STEAM',
    calorieMin: 200,
    calorieMax: 480,
    proteinMin: 24,
    fatMax: 12,
    maximumTimeMinutes: 40,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 360,
    provenance: 'METHOD_STEAM',
    rationale: 'Steam method diversity',
  }),

  // —— More wave/product slots to reach 50–80 ——
  s({
    name: 'Lunch potato+chicken MAIN',
    description: 'Обед курица с картофелем',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 350,
    calorieMax: 720,
    proteinMin: 26,
    fatMax: 26,
    maximumTimeMinutes: 50,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 370,
    provenance: 'WAVE1_CHICKEN_POTATO',
    rationale: 'potato_chicken fixture family',
  }),
  s({
    name: 'Dinner pasta+chicken MAIN',
    description: 'Ужин паста с курицей',
    mealType: 'dinner',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'BOIL',
    calorieMin: 380,
    calorieMax: 750,
    proteinMin: 24,
    fatMax: 24,
    maximumTimeMinutes: 40,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 380,
    provenance: 'WAVE1_CHICKEN_PASTA',
    rationale: 'pasta_chicken catalog dish',
  }),
  s({
    name: 'Lunch turkey+rice MAIN',
    description: 'Обед индейка с рисом',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 350,
    calorieMax: 700,
    proteinMin: 26,
    fatMax: 22,
    maximumTimeMinutes: 45,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 390,
    provenance: 'CROSS_TURKEY_RICE',
    rationale: 'rice_turkey catalog coverage',
  }),
  s({
    name: 'Dinner potato+fish MAIN',
    description: 'Ужин рыба с картофелем',
    mealType: 'dinner',
    primaryProductKey: 'pollock_raw',
    dishType: 'MAIN',
    cookingMethod: 'BAKE',
    calorieMin: 300,
    calorieMax: 650,
    proteinMin: 24,
    fatMax: 18,
    maximumTimeMinutes: 50,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'OVEN',
    priority: 'HIGH',
    sortRank: 400,
    provenance: 'WAVE1_FISH_POTATO',
    rationale: 'potato_fish catalog dish',
  }),
  s({
    name: 'Breakfast oatmeal PORRIDGE',
    description: 'Овсяная каша',
    mealType: 'breakfast',
    primaryProductKey: null,
    dishType: 'PORRIDGE',
    cookingMethod: 'BOIL',
    calorieMin: 200,
    calorieMax: 450,
    proteinMin: 7,
    fatMax: 12,
    maximumTimeMinutes: 20,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 410,
    provenance: 'CROSS_OATMEAL',
    rationale: 'oatmeal_bowl catalog',
  }),
  s({
    name: 'Lunch protein bowl',
    description: 'Протеиновый боул на обед',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'BOWL',
    cookingMethod: 'MIX',
    calorieMin: 350,
    calorieMax: 700,
    proteinMin: 30,
    fatMax: 22,
    maximumTimeMinutes: 35,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 420,
    provenance: 'CROSS_PROTEIN_BOWL',
    rationale: 'protein_power_bowl catalog',
  }),
  s({
    name: 'Snack greek yogurt',
    description: 'Йогуртовый перекус',
    mealType: 'snack',
    primaryProductKey: null,
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 100,
    calorieMax: 280,
    proteinMin: 10,
    fatMax: 10,
    maximumTimeMinutes: 5,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'MEDIUM',
    sortRank: 430,
    provenance: 'CROSS_YOGURT',
    rationale: 'greek_yogurt catalog',
  }),
  s({
    name: 'Lunch chicken peanut MAIN',
    description: 'Обед курица в арахисовом соусе/стиле',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'MAIN',
    cookingMethod: 'FRY',
    calorieMin: 380,
    calorieMax: 750,
    proteinMin: 26,
    fatMax: 30,
    maximumTimeMinutes: 40,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'LOW',
    sortRank: 440,
    provenance: 'WAVE1_CHICKEN_VARIANT',
    rationale: 'peanut_chicken — вариативность, не дубль названия',
  }),
  s({
    name: 'Dinner oven bake MAIN no product',
    description: 'Ужин в духовке без фиксированного Product',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'BAKE',
    calorieMin: 300,
    calorieMax: 650,
    proteinMin: 18,
    fatMax: 24,
    maximumTimeMinutes: 55,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'OVEN',
    priority: 'MEDIUM',
    sortRank: 450,
    provenance: 'CROSS_OVEN',
    rationale: 'Oven method coverage',
  }),
  s({
    name: 'Lunch budget MAIN stove',
    description: 'Бюджетный обед MAIN',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'BOIL',
    calorieMin: 280,
    calorieMax: 600,
    proteinMin: 16,
    fatMax: 20,
    maximumTimeMinutes: 40,
    maximumCost: 150,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 460,
    provenance: 'CROSS_BUDGET',
    rationale: 'Бюджетный обеденный слот',
  }),
  s({
    name: 'Dinner budget MAIN stove',
    description: 'Бюджетный ужин MAIN',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'MAIN',
    cookingMethod: 'STEW',
    calorieMin: 280,
    calorieMax: 600,
    proteinMin: 16,
    fatMax: 20,
    maximumTimeMinutes: 45,
    maximumCost: 150,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 470,
    provenance: 'CROSS_BUDGET',
    rationale: 'Бюджетный вечерний слот',
  }),
  s({
    name: 'Breakfast quick no gear',
    description: 'Очень быстрый завтрак без оборудования',
    mealType: 'breakfast',
    primaryProductKey: null,
    dishType: 'BREAKFAST',
    cookingMethod: 'RAW',
    calorieMin: 150,
    calorieMax: 400,
    proteinMin: 10,
    fatMax: 14,
    maximumTimeMinutes: 10,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'CRITICAL',
    sortRank: 480,
    provenance: 'CROSS_QUICK',
    rationale: 'Adherence: ultra-quick breakfast',
  }),
  s({
    name: 'Lunch salad chicken',
    description: 'Салат с курицей на обед',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'SALAD',
    cookingMethod: 'MIX',
    calorieMin: 250,
    calorieMax: 550,
    proteinMin: 24,
    fatMax: 22,
    maximumTimeMinutes: 25,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 490,
    provenance: 'WAVE1_CHICKEN_SALAD',
    rationale: 'Курица в салатном формате',
  }),
  s({
    name: 'Dinner soup chicken',
    description: 'Куриный суп на ужин',
    mealType: 'dinner',
    primaryProductKey: 'chicken_breast',
    dishType: 'SOUP',
    cookingMethod: 'BOIL',
    calorieMin: 180,
    calorieMax: 450,
    proteinMin: 18,
    fatMax: 16,
    maximumTimeMinutes: 55,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 500,
    provenance: 'WAVE1_CHICKEN_SOUP',
    rationale: 'Суп с ключевым белком',
  }),
  s({
    name: 'Afternoon high-protein cottage',
    description: 'Высокобелковый afternoon творог',
    mealType: 'afternoon_snack',
    primaryProductKey: 'cottage_cheese_2pct',
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 120,
    calorieMax: 320,
    proteinMin: 18,
    fatMax: 8,
    maximumTimeMinutes: 5,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'HIGH',
    sortRank: 510,
    provenance: 'WAVE1_COTTAGE',
    rationale: 'Дополнительный творожный band 2%',
  }),
  s({
    name: 'Snack eggs fried',
    description: 'Жареное яйцо как snack',
    mealType: 'snack',
    primaryProductKey: 'egg_fried',
    dishType: 'SNACK',
    cookingMethod: 'FRY',
    calorieMin: 120,
    calorieMax: 300,
    proteinMin: 10,
    fatMax: 20,
    maximumTimeMinutes: 12,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'LOW',
    sortRank: 520,
    provenance: 'WAVE1_EGGS',
    rationale: 'Форма FRIED как отдельный controlled band',
  }),
  s({
    name: 'Lunch vegan salad',
    description: 'Веганский салат на обед',
    mealType: 'lunch',
    primaryProductKey: null,
    dishType: 'SALAD',
    cookingMethod: 'RAW',
    calorieMin: 120,
    calorieMax: 380,
    proteinMin: 5,
    fatMax: 18,
    maximumTimeMinutes: 20,
    dietaryProfile: 'VEGAN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'LOW',
    sortRank: 530,
    provenance: 'DIET_VEGAN',
    rationale: 'Лёгкий vegan lunch',
  }),
  s({
    name: 'Dinner vegetarian soup',
    description: 'Вегетарианский суп на ужин',
    mealType: 'dinner',
    primaryProductKey: null,
    dishType: 'SOUP',
    cookingMethod: 'BOIL',
    calorieMin: 150,
    calorieMax: 420,
    proteinMin: 6,
    fatMax: 14,
    maximumTimeMinutes: 45,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'MEDIUM',
    sortRank: 540,
    provenance: 'DIET_VEGETARIAN',
    rationale: 'VEGETARIAN soup evening',
  }),
  s({
    name: 'Lunch grill bowl chicken',
    description: 'Гриль-боул с курицей',
    mealType: 'lunch',
    primaryProductKey: 'chicken_breast',
    dishType: 'BOWL',
    cookingMethod: 'GRILL',
    calorieMin: 350,
    calorieMax: 700,
    proteinMin: 28,
    fatMax: 24,
    maximumTimeMinutes: 35,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 550,
    provenance: 'WAVE1_CHICKEN_BOWL',
    rationale: 'grilled_chicken_bowl catalog',
  }),
  s({
    name: 'Breakfast eggs HIGH_PROTEIN',
    description: 'Высокобелковый яичный завтрак',
    mealType: 'breakfast',
    primaryProductKey: 'eggs',
    dishType: 'BREAKFAST',
    cookingMethod: 'FRY',
    calorieMin: 220,
    calorieMax: 480,
    proteinMin: 20,
    fatMax: 28,
    maximumTimeMinutes: 15,
    dietaryProfile: 'HIGH_PROTEIN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 560,
    provenance: 'WAVE1_EGGS',
    rationale: 'HP breakfast eggs',
  }),
  s({
    name: 'Dinner pollock baked form',
    description: 'Ужин с pollock_baked как primary form',
    mealType: 'dinner',
    primaryProductKey: 'pollock_baked',
    dishType: 'MAIN',
    cookingMethod: 'BAKE',
    calorieMin: 220,
    calorieMax: 520,
    proteinMin: 24,
    fatMax: 14,
    maximumTimeMinutes: 40,
    dietaryProfile: 'GENERAL',
    equipmentProfile: 'OVEN',
    priority: 'MEDIUM',
    sortRank: 570,
    provenance: 'WAVE1_POLLOCK',
    rationale: 'Form BAKED как отдельный primary Product lineage slot',
  }),
  s({
    name: 'Lunch side buckwheat boiled',
    description: 'Гарнир гречка варёная на обед',
    mealType: 'lunch',
    primaryProductKey: 'buckwheat_boiled',
    dishType: 'SIDE',
    cookingMethod: 'BOIL',
    calorieMin: 150,
    calorieMax: 380,
    proteinMin: 5,
    fatMax: 10,
    maximumTimeMinutes: 30,
    dietaryProfile: 'VEGAN',
    equipmentProfile: 'BASIC_STOVE',
    priority: 'HIGH',
    sortRank: 580,
    provenance: 'WAVE1_BUCKWHEAT',
    rationale: 'BOILED form slot',
  }),
  s({
    name: 'Snack cottage 9pct',
    description: 'Творог 9% как snack',
    mealType: 'snack',
    primaryProductKey: 'cottage_cheese_9pct',
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 140,
    calorieMax: 360,
    proteinMin: 14,
    fatMax: 16,
    maximumTimeMinutes: 5,
    dietaryProfile: 'VEGETARIAN',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'LOW',
    sortRank: 590,
    provenance: 'WAVE1_COTTAGE',
    rationale: 'Жирностный band 9%',
  }),
  s({
    name: 'Afternoon gluten-free snack',
    description: 'GF afternoon snack',
    mealType: 'afternoon_snack',
    primaryProductKey: null,
    dishType: 'SNACK',
    cookingMethod: 'RAW',
    calorieMin: 80,
    calorieMax: 260,
    proteinMin: 5,
    fatMax: 12,
    maximumTimeMinutes: 10,
    dietaryProfile: 'GLUTEN_FREE',
    equipmentProfile: 'NO_SPECIAL_EQUIPMENT',
    priority: 'LOW',
    sortRank: 600,
    provenance: 'DIET_GF',
    rationale: 'GF snack structural',
  }),
];

export const COVERAGE_CORE_V1_SLOT_COUNT = COVERAGE_CORE_V1_SLOTS.length;
