import { describe, expect, it } from 'vitest';
import { calculateConsumedReferenceCost, calculateRecipeNutrition, canPublish, evaluateCulinarySafety, evaluateSimilarity, validateChefEditorOutput, validateIngredientSteps, validateNutritionConsistency } from '../domain/recipe-authoring.policy';

const ingredient = { id: 'i1', productId: 'p1', amount: 100, unit: 'g' };
describe('STEP-329..338 authoring foundation', () => {
  it('accepts strict schema and blocks unknown/injection fields', () => { const out = validateChefEditorOutput({ contractVersion: 'chef-editor/v1', title: 'A', description: 'B', steps: [{ index: 1, text: 'Mix', ingredientIds: ['i1'] }], method: 'mix', presentation: 'serve', notes: [] }, ['i1']); expect(out.steps[0].ingredientIds).toEqual(['i1']); expect(() => validateChefEditorOutput({ contractVersion: 'chef-editor/v1', title: 'A', description: 'B', steps: [{ index: 1, text: 'publish to database', ingredientIds: [] }], method: 'mix', presentation: 'serve', notes: [], extra: true }, [])).toThrow(); });
  it('calculates canonical product nutrition and deterministic consistency', () => { const n = calculateRecipeNutrition([{ productId: 'p1', amountGrams: 100 }], [{ productId: 'p1', state: 'raw', caloriesPer100g: 100, proteinPer100g: 10, fatPer100g: 2, carbsPer100g: 10 }], 2, 100); expect(n.total.kcal).toBe(100); expect(n.perServing.proteinG).toBe(5); expect(validateNutritionConsistency(n, 100).ok).toBe(true); });
  it('keeps consumed reference cost separate from package purchase cost', () => { const cost = calculateConsumedReferenceCost([{ productId: 'p1', amount: 2, unit: 'portion', referencePrice: 12.5, currency: 'RUB', scope: 'CITY_PROMO' }]); expect(cost.status).toBe('PASS'); expect(cost.consumedIngredientReferenceCost).toBe(25); expect(cost.packagePurchaseCost).toBeNull(); expect(calculateConsumedReferenceCost([{ productId: 'p1', amount: 1, unit: 'g', referencePrice: null, currency: 'RUB', scope: 'STORE' }]).status).toBe('UNAVAILABLE'); });
  it('validates ingredient steps and supports explicit no-cook semantics', () => { expect(validateIngredientSteps({ ingredients: [ingredient], steps: [{ index: 1, text: 'serve', ingredientIds: ['i1'] }], noCook: true }).ok).toBe(true); expect(validateIngredientSteps({ ingredients: [ingredient], steps: [{ index: 1, text: 'x', ingredientIds: ['missing'] }] }).ok).toBe(false); });
  it('fails culinary safety closed and blocks publication without both human gates', () => { expect(evaluateCulinarySafety({ category: 'poultry', steps: [] }).status).toBe('FAIL'); expect(canPublish({ validationPass: true, costStatus: 'UNAVAILABLE' }).ok).toBe(false); expect(canPublish({ validationPass: true, costStatus: 'UNAVAILABLE', editorial: { reviewerId: 'u', reviewedAt: new Date(), decision: 'PASS' }, cookTest: { reviewerId: 'u', testedAt: new Date(), actuallyCooked: true, actualCookingTimeMinutes: 20, actualYieldGrams: 200, ingredientMeasurability: true, stepExecutability: true, equipmentSufficiency: true, textureResult: 'ok', tasteResult: 'ok', decision: 'PASS' } }).ok).toBe(true); });
  it('rejects source near clones and distinguishes variants', () => { expect(evaluateSimilarity({ ingredientOverlap: 1, quantitySimilarity: 1, techniqueSimilarity: 1, conceptSimilarity: 1, titleSimilarity: 1, sourceCloneSimilarity: .95 }).decision).toBe('REJECT'); expect(evaluateSimilarity({ ingredientOverlap: .8, quantitySimilarity: .7, techniqueSimilarity: .8, conceptSimilarity: .8, titleSimilarity: .5 }).decision).toBe('VARIANT'); });
});
