export const CATALOG_CORE_V3_EXPANSION_ROWS = [
  {
    "n": 201,
    "key": "duck_breast_raw",
    "name": "Грудка утки",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 240,
    "p": 19,
    "f": 18,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 202,
    "key": "lamb_leg_raw",
    "name": "Баранина нога",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 232,
    "p": 18,
    "f": 17,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf"
  },
  {
    "n": 203,
    "key": "veal_lean_raw",
    "name": "Телятина постная",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 172,
    "p": 20,
    "f": 9,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 204,
    "key": "chicken_wing_raw",
    "name": "Куриные крылья",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 191,
    "p": 18,
    "f": 13,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 205,
    "key": "turkey_thigh_raw",
    "name": "Индейка бедро",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 144,
    "p": 19,
    "f": 7,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 206,
    "key": "pork_mince_raw",
    "name": "Фарш свиной",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 263,
    "p": 17,
    "f": 21,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 207,
    "key": "chicken_liver_raw",
    "name": "Печень куриная",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 119,
    "p": 17,
    "f": 4.7,
    "c": 1.1,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 208,
    "key": "beef_heart_raw",
    "name": "Сердце говяжье",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 112,
    "p": 17,
    "f": 3.9,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 209,
    "key": "goose_raw",
    "name": "Гусь",
    "cat": "meat_poultry",
    "form": "RAW",
    "cal": 371,
    "p": 16,
    "f": 34,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf"
  },
  {
    "n": 210,
    "key": "chicken_stewed",
    "name": "Курица тушёная",
    "cat": "meat_poultry",
    "form": "STEWED",
    "cal": 184,
    "p": 25,
    "f": 9,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 211,
    "key": "pork_baked",
    "name": "Свинина запечённая",
    "cat": "meat_poultry",
    "form": "BAKED",
    "cal": 242,
    "p": 27,
    "f": 14,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda"
  },
  {
    "n": 212,
    "key": "beef_boiled",
    "name": "Говядина варёная",
    "cat": "meat_poultry",
    "form": "BOILED",
    "cal": 254,
    "p": 26,
    "f": 17,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf"
  },
  {
    "n": 213,
    "key": "carp_raw",
    "name": "Карп",
    "cat": "fish_seafood",
    "form": "RAW",
    "cal": 127,
    "p": 18,
    "f": 5.3,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf",
    "allergen": "fish"
  },
  {
    "n": 214,
    "key": "pike_raw",
    "name": "Щука",
    "cat": "fish_seafood",
    "form": "RAW",
    "cal": 84,
    "p": 18,
    "f": 0.8,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf",
    "allergen": "fish"
  },
  {
    "n": 215,
    "key": "trout_raw",
    "name": "Форель",
    "cat": "fish_seafood",
    "form": "RAW",
    "cal": 148,
    "p": 21,
    "f": 7,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "allergen": "fish"
  },
  {
    "n": 216,
    "key": "sardine_canned_drained",
    "name": "Сардины консервированные",
    "cat": "fish_seafood",
    "form": "DRAINED",
    "cal": 208,
    "p": 25,
    "f": 11,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "allergen": "fish"
  },
  {
    "n": 217,
    "key": "crab_sticks",
    "name": "Крабовые палочки",
    "cat": "fish_seafood",
    "form": "READY_TO_EAT",
    "cal": 87,
    "p": 6,
    "f": 1.5,
    "c": 13,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "allergen": "shellfish"
  },
  {
    "n": 218,
    "key": "mussels_raw",
    "name": "Мидии",
    "cat": "fish_seafood",
    "form": "RAW",
    "cal": 86,
    "p": 12,
    "f": 2.2,
    "c": 3.7,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "allergen": "shellfish"
  },
  {
    "n": 219,
    "key": "salmon_boiled",
    "name": "Лосось варёный",
    "cat": "fish_seafood",
    "form": "BOILED",
    "cal": 184,
    "p": 22,
    "f": 10,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "allergen": "fish"
  },
  {
    "n": 220,
    "key": "cod_boiled",
    "name": "Треска варёная",
    "cat": "fish_seafood",
    "form": "BOILED",
    "cal": 78,
    "p": 18,
    "f": 0.6,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf",
    "allergen": "fish"
  },
  {
    "n": 221,
    "key": "pollock_baked",
    "name": "Минтай запечённый",
    "cat": "fish_seafood",
    "form": "BAKED",
    "cal": 86,
    "p": 19,
    "f": 1,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf",
    "allergen": "fish"
  },
  {
    "n": 222,
    "key": "caviar_red",
    "name": "Икра красная",
    "cat": "fish_seafood",
    "form": "READY_TO_EAT",
    "cal": 249,
    "p": 32,
    "f": 13,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "rf",
    "allergen": "fish"
  },
  {
    "n": 223,
    "key": "milk_2_5pct",
    "name": "Молоко питьевое 2.5%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 60,
    "p": 3.2,
    "f": 2.5,
    "c": 4.7,
    "fatPct": 2.5,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "rf",
    "aliases": [
      "молоко 2.5 питьевое"
    ]
  },
  {
    "n": 224,
    "key": "kefir_1pct",
    "name": "Кефир 1%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 40,
    "p": 3,
    "f": 1,
    "c": 4,
    "fatPct": 1,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 225,
    "key": "yogurt_greek_2pct",
    "name": "Греческий йогурт 2%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 73,
    "p": 10,
    "f": 2,
    "c": 3.6,
    "fatPct": 2,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 226,
    "key": "cottage_cheese_2pct",
    "name": "Творог 2%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 103,
    "p": 18,
    "f": 2,
    "c": 3.3,
    "fatPct": 2,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 227,
    "key": "sour_cream_15pct",
    "name": "Сметана 15%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 162,
    "p": 2.6,
    "f": 15,
    "c": 3,
    "fatPct": 15,
    "allergen": "milk",
    "role": "FAT",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 228,
    "key": "sour_cream_10pct",
    "name": "Сметана 10%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 115,
    "p": 3,
    "f": 10,
    "c": 2.9,
    "fatPct": 10,
    "allergen": "milk",
    "role": "FAT",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 229,
    "key": "cheese_mozzarella",
    "name": "Моцарелла",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 280,
    "p": 28,
    "f": 17,
    "c": 3.1,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 230,
    "key": "cheese_feta",
    "name": "Фета",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 264,
    "p": 14,
    "f": 21,
    "c": 4.1,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 231,
    "key": "cream_10pct",
    "name": "Сливки 10%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 118,
    "p": 3,
    "f": 10,
    "c": 4,
    "fatPct": 10,
    "allergen": "milk",
    "role": "FAT",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 232,
    "key": "butter_72pct",
    "name": "Масло сливочное 72.5%",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 662,
    "p": 0.5,
    "f": 72.5,
    "c": 0.8,
    "fatPct": 72.5,
    "allergen": "milk",
    "role": "FAT",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 233,
    "key": "egg_omelette",
    "name": "Омлет",
    "cat": "eggs",
    "form": "FRIED",
    "cal": 154,
    "p": 11,
    "f": 12,
    "c": 0.6,
    "allergen": "eggs",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true
  },
  {
    "n": 234,
    "key": "quail_egg_raw",
    "name": "Яйцо перепелиное",
    "cat": "eggs",
    "form": "RAW",
    "cal": 168,
    "p": 13,
    "f": 11,
    "c": 0.4,
    "allergen": "eggs",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 235,
    "key": "wheat_groats_dry",
    "name": "Пшеничная крупа",
    "cat": "grains",
    "form": "DRY",
    "cal": 342,
    "p": 12,
    "f": 1.5,
    "c": 70,
    "role": "STARCH",
    "vegan": false,
    "veg": true,
    "allergen": "gluten",
    "review": true,
    "src": "rf"
  },
  {
    "n": 236,
    "key": "corn_grits_dry",
    "name": "Кукурузная крупа",
    "cat": "grains",
    "form": "DRY",
    "cal": 337,
    "p": 8.3,
    "f": 1.2,
    "c": 75,
    "role": "STARCH",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 237,
    "key": "spelt_dry",
    "name": "Полба сухая",
    "cat": "grains",
    "form": "DRY",
    "cal": 338,
    "p": 15,
    "f": 2.4,
    "c": 70,
    "role": "STARCH",
    "vegan": false,
    "veg": true,
    "allergen": "gluten",
    "review": true,
    "src": "usda"
  },
  {
    "n": 238,
    "key": "wild_rice_dry",
    "name": "Дикий рис сухой",
    "cat": "grains",
    "form": "DRY",
    "cal": 357,
    "p": 15,
    "f": 1.1,
    "c": 75,
    "role": "STARCH",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 239,
    "key": "wild_rice_boiled",
    "name": "Дикий рис варёный",
    "cat": "grains",
    "form": "BOILED",
    "cal": 101,
    "p": 4,
    "f": 0.3,
    "c": 21,
    "role": "STARCH",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 240,
    "key": "oatmeal_boiled",
    "name": "Каша овсяная на воде",
    "cat": "grains",
    "form": "BOILED",
    "cal": 71,
    "p": 2.5,
    "f": 1.5,
    "c": 12,
    "role": "STARCH",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda",
    "aliases": [
      "овсянка варёная на воде"
    ]
  },
  {
    "n": 241,
    "key": "semolina_boiled",
    "name": "Манная каша",
    "cat": "grains",
    "form": "BOILED",
    "cal": 98,
    "p": 3,
    "f": 3.2,
    "c": 15,
    "role": "STARCH",
    "vegan": false,
    "veg": true,
    "allergen": "gluten",
    "review": true,
    "src": "rf"
  },
  {
    "n": 242,
    "key": "couscous_boiled",
    "name": "Кускус варёный",
    "cat": "grains",
    "form": "BOILED",
    "cal": 112,
    "p": 3.8,
    "f": 0.2,
    "c": 23,
    "role": "STARCH",
    "vegan": false,
    "veg": true,
    "allergen": "gluten",
    "review": true,
    "src": "usda"
  },
  {
    "n": 243,
    "key": "pasta_dry",
    "name": "Макароны сухие",
    "cat": "pasta",
    "form": "DRY",
    "cal": 371,
    "p": 13,
    "f": 1.5,
    "c": 75,
    "allergen": "gluten",
    "role": "STARCH",
    "veg": true,
    "vegan": false,
    "review": true
  },
  {
    "n": 244,
    "key": "spaghetti_dry",
    "name": "Спагетти сухие",
    "cat": "pasta",
    "form": "DRY",
    "cal": 371,
    "p": 13,
    "f": 1.5,
    "c": 75,
    "allergen": "gluten",
    "role": "STARCH",
    "veg": true,
    "vegan": false,
    "review": true
  },
  {
    "n": 245,
    "key": "penne_dry",
    "name": "Пенне сухие",
    "cat": "pasta",
    "form": "DRY",
    "cal": 359,
    "p": 13,
    "f": 1.5,
    "c": 72,
    "allergen": "gluten",
    "role": "STARCH",
    "veg": true,
    "vegan": false,
    "review": true
  },
  {
    "n": 246,
    "key": "lasagna_sheets_dry",
    "name": "Листы лазаньи",
    "cat": "pasta",
    "form": "DRY",
    "cal": 355,
    "p": 12,
    "f": 1.5,
    "c": 72,
    "allergen": "gluten",
    "role": "STARCH",
    "veg": true,
    "vegan": false,
    "review": true
  },
  {
    "n": 247,
    "key": "rice_noodles_dry",
    "name": "Рисовая лапша сухая",
    "cat": "pasta",
    "form": "DRY",
    "cal": 364,
    "p": 3.4,
    "f": 0.6,
    "c": 83,
    "role": "STARCH",
    "veg": true,
    "vegan": true,
    "review": true
  },
  {
    "n": 248,
    "key": "soba_dry",
    "name": "Соба сухая",
    "cat": "pasta",
    "form": "DRY",
    "cal": 348,
    "p": 14,
    "f": 1,
    "c": 75,
    "allergen": "gluten",
    "role": "STARCH",
    "veg": true,
    "vegan": false,
    "review": true
  },
  {
    "n": 249,
    "key": "cauliflower_raw",
    "name": "Цветная капуста",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 25,
    "p": 1.9,
    "f": 0.3,
    "c": 5,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 250,
    "key": "brussels_sprouts_raw",
    "name": "Брюссельская капуста",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 43,
    "p": 3.4,
    "f": 0.3,
    "c": 9,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 251,
    "key": "kohlrabi_raw",
    "name": "Кольраби",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 27,
    "p": 1.7,
    "f": 0.1,
    "c": 6,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 252,
    "key": "turnip_raw",
    "name": "Репа",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 28,
    "p": 0.9,
    "f": 0.1,
    "c": 6.4,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 253,
    "key": "rutabaga_raw",
    "name": "Брюква",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 37,
    "p": 1.2,
    "f": 0.2,
    "c": 8.6,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 254,
    "key": "leek_raw",
    "name": "Лук-порей",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 61,
    "p": 1.5,
    "f": 0.3,
    "c": 14,
    "role": "AROMATIC",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 255,
    "key": "shallot_raw",
    "name": "Шалот",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 72,
    "p": 2.5,
    "f": 0.1,
    "c": 17,
    "role": "AROMATIC",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 256,
    "key": "asparagus_raw",
    "name": "Спаржа",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 20,
    "p": 2.2,
    "f": 0.1,
    "c": 3.9,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 257,
    "key": "artichoke_raw",
    "name": "Артишок",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 47,
    "p": 3.3,
    "f": 0.2,
    "c": 11,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 258,
    "key": "fennel_raw",
    "name": "Фенхель",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 31,
    "p": 1.2,
    "f": 0.2,
    "c": 7,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 259,
    "key": "chard_raw",
    "name": "Мангольд",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 19,
    "p": 1.8,
    "f": 0.2,
    "c": 3.7,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 260,
    "key": "kale_raw",
    "name": "Кейл",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 49,
    "p": 4.3,
    "f": 0.9,
    "c": 9,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 261,
    "key": "bok_choy_raw",
    "name": "Бок-чой",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 13,
    "p": 1.5,
    "f": 0.2,
    "c": 2.2,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 262,
    "key": "tomato_cherry_raw",
    "name": "Томаты черри",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 18,
    "p": 0.9,
    "f": 0.2,
    "c": 3.9,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 263,
    "key": "cucumber_pickled",
    "name": "Огурец маринованный",
    "cat": "vegetables",
    "form": "READY_TO_EAT",
    "cal": 11,
    "p": 0.3,
    "f": 0.1,
    "c": 2.3,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 264,
    "key": "sauerkraut",
    "name": "Квашеная капуста",
    "cat": "vegetables",
    "form": "READY_TO_EAT",
    "cal": 19,
    "p": 0.9,
    "f": 0.1,
    "c": 4.3,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 265,
    "key": "pepper_hot_raw",
    "name": "Перец острый",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 40,
    "p": 1.9,
    "f": 0.4,
    "c": 9,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 266,
    "key": "ginger_fresh",
    "name": "Имбирь свежий",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 80,
    "p": 1.8,
    "f": 0.8,
    "c": 18,
    "role": "AROMATIC",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 267,
    "key": "potato_fried",
    "name": "Картофель жареный",
    "cat": "vegetables",
    "form": "FRIED",
    "cal": 192,
    "p": 2.5,
    "f": 9,
    "c": 26,
    "role": "STARCH",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 268,
    "key": "onion_baked",
    "name": "Лук запечённый",
    "cat": "vegetables",
    "form": "BAKED",
    "cal": 44,
    "p": 1.2,
    "f": 0.2,
    "c": 10,
    "role": "AROMATIC",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 269,
    "key": "beet_boiled",
    "name": "Свёкла варёная",
    "cat": "vegetables",
    "form": "BOILED",
    "cal": 44,
    "p": 1.7,
    "f": 0.2,
    "c": 10,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 270,
    "key": "cabbage_stewed",
    "name": "Капуста тушёная",
    "cat": "vegetables",
    "form": "STEWED",
    "cal": 47,
    "p": 1.8,
    "f": 2.8,
    "c": 5.2,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 271,
    "key": "mushroom_oyster_raw",
    "name": "Вёшенки",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 33,
    "p": 3.3,
    "f": 0.4,
    "c": 6.1,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 272,
    "key": "seaweed_nori",
    "name": "Нори",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 35,
    "p": 5.8,
    "f": 0.3,
    "c": 5.1,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 273,
    "key": "sweet_potato_raw",
    "name": "Батат",
    "cat": "vegetables",
    "form": "RAW",
    "cal": 86,
    "p": 1.6,
    "f": 0.1,
    "c": 20,
    "role": "STARCH",
    "vegan": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 274,
    "key": "apricot_raw",
    "name": "Абрикос",
    "cat": "fruits",
    "form": "RAW",
    "cal": 48,
    "p": 1.4,
    "f": 0.4,
    "c": 11,
    "vegan": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 275,
    "key": "peach_raw",
    "name": "Персик",
    "cat": "fruits",
    "form": "RAW",
    "cal": 39,
    "p": 0.9,
    "f": 0.3,
    "c": 10,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 276,
    "key": "nectarine_raw",
    "name": "Нектарин",
    "cat": "fruits",
    "form": "RAW",
    "cal": 44,
    "p": 1.1,
    "f": 0.3,
    "c": 11,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 277,
    "key": "mango_raw",
    "name": "Манго",
    "cat": "fruits",
    "form": "RAW",
    "cal": 60,
    "p": 0.8,
    "f": 0.4,
    "c": 15,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 278,
    "key": "papaya_raw",
    "name": "Папайя",
    "cat": "fruits",
    "form": "RAW",
    "cal": 43,
    "p": 0.5,
    "f": 0.3,
    "c": 11,
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 279,
    "key": "pomegranate_raw",
    "name": "Гранат",
    "cat": "fruits",
    "form": "RAW",
    "cal": 83,
    "p": 1.7,
    "f": 1.2,
    "c": 19,
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 280,
    "key": "fig_raw",
    "name": "Инжир",
    "cat": "fruits",
    "form": "RAW",
    "cal": 74,
    "p": 0.8,
    "f": 0.3,
    "c": 19,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 281,
    "key": "persimmon_raw",
    "name": "Хурма",
    "cat": "fruits",
    "form": "RAW",
    "cal": 70,
    "p": 0.6,
    "f": 0.2,
    "c": 19,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 282,
    "key": "cranberry_raw",
    "name": "Клюква",
    "cat": "fruits",
    "form": "RAW",
    "cal": 46,
    "p": 0.4,
    "f": 0.1,
    "c": 12,
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 283,
    "key": "raspberry_raw",
    "name": "Малина",
    "cat": "fruits",
    "form": "RAW",
    "cal": 52,
    "p": 1.2,
    "f": 0.7,
    "c": 12,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 284,
    "key": "blackberry_raw",
    "name": "Ежевика",
    "cat": "fruits",
    "form": "RAW",
    "cal": 43,
    "p": 1.4,
    "f": 0.5,
    "c": 10,
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 285,
    "key": "currant_black_raw",
    "name": "Смородина чёрная",
    "cat": "fruits",
    "form": "RAW",
    "cal": 63,
    "p": 1.4,
    "f": 0.4,
    "c": 15,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 286,
    "key": "gooseberry_raw",
    "name": "Крыжовник",
    "cat": "fruits",
    "form": "RAW",
    "cal": 44,
    "p": 0.9,
    "f": 0.6,
    "c": 10,
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 287,
    "key": "melon_raw",
    "name": "Дыня",
    "cat": "fruits",
    "form": "RAW",
    "cal": 34,
    "p": 0.8,
    "f": 0.2,
    "c": 8.2,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 288,
    "key": "grapefruit_raw",
    "name": "Грейпфрут",
    "cat": "fruits",
    "form": "RAW",
    "cal": 42,
    "p": 0.8,
    "f": 0.1,
    "c": 11,
    "role": "ACID",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 289,
    "key": "lime_raw",
    "name": "Лайм",
    "cat": "fruits",
    "form": "RAW",
    "cal": 30,
    "p": 0.7,
    "f": 0.2,
    "c": 11,
    "role": "ACID",
    "vegan": true,
    "review": false,
    "src": "rf"
  },
  {
    "n": 290,
    "key": "tangerine_raw",
    "name": "Мандарин",
    "cat": "fruits",
    "form": "RAW",
    "cal": 53,
    "p": 0.8,
    "f": 0.3,
    "c": 13,
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 291,
    "key": "dried_apricot",
    "name": "Курага",
    "cat": "fruits",
    "form": "DRY",
    "cal": 241,
    "p": 3.4,
    "f": 0.5,
    "c": 63,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 292,
    "key": "raisin",
    "name": "Изюм",
    "cat": "fruits",
    "form": "DRY",
    "cal": 299,
    "p": 3.1,
    "f": 0.5,
    "c": 79,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 293,
    "key": "date_dried",
    "name": "Финик сушёный",
    "cat": "fruits",
    "form": "DRY",
    "cal": 282,
    "p": 2.5,
    "f": 0.4,
    "c": 75,
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 294,
    "key": "lentils_red_dry",
    "name": "Чечевица красная сухая",
    "cat": "legumes",
    "form": "DRY",
    "cal": 358,
    "p": 24,
    "f": 1.5,
    "c": 63,
    "role": "MAIN_PROTEIN",
    "vegan": true,
    "review": true
  },
  {
    "n": 295,
    "key": "mung_beans_dry",
    "name": "Маш сухой",
    "cat": "legumes",
    "form": "DRY",
    "cal": 347,
    "p": 24,
    "f": 1.2,
    "c": 63,
    "role": "MAIN_PROTEIN",
    "vegan": true,
    "review": true
  },
  {
    "n": 296,
    "key": "soybeans_dry",
    "name": "Соя сухая",
    "cat": "legumes",
    "form": "DRY",
    "cal": 446,
    "p": 36,
    "f": 20,
    "c": 30,
    "role": "MAIN_PROTEIN",
    "vegan": true,
    "review": true,
    "allergen": "soy"
  },
  {
    "n": 297,
    "key": "tofu_firm",
    "name": "Тофу плотный",
    "cat": "legumes",
    "form": "READY_TO_EAT",
    "cal": 144,
    "p": 17,
    "f": 9,
    "c": 3,
    "role": "MAIN_PROTEIN",
    "vegan": true,
    "review": true,
    "allergen": "soy"
  },
  {
    "n": 298,
    "key": "green_peas_fresh",
    "name": "Горошек зелёный",
    "cat": "legumes",
    "form": "RAW",
    "cal": 81,
    "p": 5.4,
    "f": 0.4,
    "c": 14,
    "role": "MAIN_PROTEIN",
    "vegan": true,
    "review": true
  },
  {
    "n": 299,
    "key": "beans_canned_drained",
    "name": "Фасоль консервированная",
    "cat": "legumes",
    "form": "DRAINED",
    "cal": 90,
    "p": 6,
    "f": 0.4,
    "c": 16,
    "role": "MAIN_PROTEIN",
    "vegan": true,
    "review": true
  },
  {
    "n": 300,
    "key": "linseed_oil",
    "name": "Льняное масло",
    "cat": "oils_fats",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 884,
    "p": 0,
    "f": 100,
    "c": 0,
    "role": "FAT",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 301,
    "key": "corn_oil",
    "name": "Кукурузное масло",
    "cat": "oils_fats",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 884,
    "p": 0,
    "f": 100,
    "c": 0,
    "role": "FAT",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 302,
    "key": "coconut_oil",
    "name": "Кокосовое масло",
    "cat": "oils_fats",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 862,
    "p": 0,
    "f": 100,
    "c": 0,
    "role": "FAT",
    "vegan": true,
    "review": false,
    "src": "usda"
  },
  {
    "n": 303,
    "key": "lard",
    "name": "Смалец",
    "cat": "oils_fats",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 902,
    "p": 0,
    "f": 100,
    "c": 0,
    "role": "FAT",
    "vegan": false,
    "review": true,
    "src": "rf"
  },
  {
    "n": 304,
    "key": "adjika",
    "name": "Аджика",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 59,
    "p": 1,
    "f": 3,
    "c": 7,
    "role": "SAUCE_BASE",
    "vegan": true,
    "review": true
  },
  {
    "n": 305,
    "key": "horseradish",
    "name": "Хрен столовый",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 48,
    "p": 1.2,
    "f": 0.2,
    "c": 11,
    "role": "SAUCE_BASE",
    "vegan": true,
    "review": true
  },
  {
    "n": 306,
    "key": "mustard_dijon",
    "name": "Горчица дижонская",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 66,
    "p": 4.4,
    "f": 3.3,
    "c": 5,
    "role": "SAUCE_BASE",
    "vegan": true,
    "allergen": "mustard",
    "review": true
  },
  {
    "n": 307,
    "key": "pesto",
    "name": "Песто",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 263,
    "p": 3.5,
    "f": 25,
    "c": 6,
    "role": "FAT",
    "vegan": true,
    "review": true
  },
  {
    "n": 308,
    "key": "teriyaki",
    "name": "Терияки",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 89,
    "p": 5.9,
    "f": 0,
    "c": 15,
    "role": "SAUCE_BASE",
    "vegan": true,
    "allergen": "soy",
    "review": true
  },
  {
    "n": 309,
    "key": "bbq_sauce",
    "name": "Соус барбекю",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 172,
    "p": 0.8,
    "f": 0.6,
    "c": 41,
    "role": "SAUCE_BASE",
    "vegan": true,
    "review": true
  },
  {
    "n": 310,
    "key": "tahini",
    "name": "Тахини",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 595,
    "p": 17,
    "f": 54,
    "c": 21,
    "role": "FAT",
    "vegan": true,
    "allergen": "sesame",
    "review": true
  },
  {
    "n": 311,
    "key": "salsa",
    "name": "Сальса",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 36,
    "p": 1.5,
    "f": 0.2,
    "c": 7,
    "role": "SAUCE_BASE",
    "vegan": true,
    "review": true
  },
  {
    "n": 312,
    "key": "soy_sauce_light",
    "name": "Соевый соус светлый",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 53,
    "p": 8,
    "f": 0,
    "c": 5,
    "role": "SAUCE_BASE",
    "vegan": true,
    "allergen": "soy",
    "review": true
  },
  {
    "n": 313,
    "key": "fish_sauce",
    "name": "Рыбный соус",
    "cat": "sauces",
    "form": "READY_TO_EAT",
    "cal": 35,
    "p": 5,
    "f": 0,
    "c": 4,
    "role": "SAUCE_BASE",
    "vegan": false,
    "allergen": "fish",
    "review": true
  },
  {
    "n": 314,
    "key": "basil_dried",
    "name": "Базилик сушёный",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 233,
    "p": 23,
    "f": 4,
    "c": 47,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 315,
    "key": "thyme_dried",
    "name": "Тимьян сушёный",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 276,
    "p": 9,
    "f": 7.4,
    "c": 64,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 316,
    "key": "rosemary_dried",
    "name": "Розмарин сушёный",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 331,
    "p": 4.9,
    "f": 15,
    "c": 64,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 317,
    "key": "coriander_seed",
    "name": "Кориандр семена",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 298,
    "p": 12,
    "f": 17,
    "c": 55,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 318,
    "key": "cardamom",
    "name": "Кардамон",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 311,
    "p": 11,
    "f": 6.7,
    "c": 68,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 319,
    "key": "clove",
    "name": "Гвоздика",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 274,
    "p": 6,
    "f": 13,
    "c": 66,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 320,
    "key": "nutmeg",
    "name": "Мускатный орех",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 525,
    "p": 6,
    "f": 36,
    "c": 49,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 321,
    "key": "turmeric",
    "name": "Куркума",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 312,
    "p": 10,
    "f": 3.3,
    "c": 67,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 322,
    "key": "chili_powder",
    "name": "Перец чили молотый",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 282,
    "p": 13,
    "f": 14,
    "c": 50,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 323,
    "key": "garlic_powder",
    "name": "Чеснок сушёный",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 331,
    "p": 17,
    "f": 0.7,
    "c": 73,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 324,
    "key": "onion_powder",
    "name": "Лук сушёный",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 341,
    "p": 10,
    "f": 1,
    "c": 79,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 325,
    "key": "parsley_dried",
    "name": "Петрушка сушёная",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 292,
    "p": 27,
    "f": 5.5,
    "c": 51,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 326,
    "key": "mint_dried",
    "name": "Мята сушёная",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 285,
    "p": 20,
    "f": 6,
    "c": 52,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 327,
    "key": "saffron",
    "name": "Шафран",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 310,
    "p": 11,
    "f": 5.9,
    "c": 65,
    "role": "SEASONING",
    "vegan": true,
    "review": true
  },
  {
    "n": 328,
    "key": "allspice",
    "name": "Душистый перец",
    "cat": "spices",
    "form": "DRY",
    "unit": "g",
    "cal": 263,
    "p": 6.1,
    "f": 8.7,
    "c": 72,
    "role": "SEASONING",
    "vegan": true,
    "review": false
  },
  {
    "n": 329,
    "key": "rye_flour",
    "name": "Мука ржаная",
    "cat": "technological_ingredients",
    "form": "DRY",
    "unit": "g",
    "cal": 349,
    "p": 11,
    "f": 1.7,
    "c": 76,
    "role": "BINDER",
    "allergen": "gluten",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 330,
    "key": "corn_flour",
    "name": "Мука кукурузная",
    "cat": "technological_ingredients",
    "form": "DRY",
    "unit": "g",
    "cal": 361,
    "p": 7,
    "f": 3.9,
    "c": 77,
    "role": "BINDER",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 331,
    "key": "buckwheat_flour",
    "name": "Мука гречневая",
    "cat": "technological_ingredients",
    "form": "DRY",
    "unit": "g",
    "cal": 335,
    "p": 13,
    "f": 3.1,
    "c": 71,
    "role": "BINDER",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "rf"
  },
  {
    "n": 332,
    "key": "rice_flour",
    "name": "Мука рисовая",
    "cat": "technological_ingredients",
    "form": "DRY",
    "unit": "g",
    "cal": 366,
    "p": 6,
    "f": 1.4,
    "c": 80,
    "role": "BINDER",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 333,
    "key": "powdered_sugar",
    "name": "Сахарная пудра",
    "cat": "technological_ingredients",
    "form": "DRY",
    "unit": "g",
    "cal": 389,
    "p": 0,
    "f": 0,
    "c": 100,
    "role": "SEASONING",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 334,
    "key": "vinegar_apple",
    "name": "Уксус яблочный",
    "cat": "technological_ingredients",
    "form": "READY_TO_EAT",
    "unit": "ml",
    "cal": 21,
    "p": 0,
    "f": 0,
    "c": 0.9,
    "role": "ACID",
    "vegan": true,
    "veg": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 335,
    "key": "tomato_raw",
    "name": "Помидор",
    "cat": "vegetables",
    "form": "RAW",
    "unit": "g",
    "cal": 18,
    "p": 0.9,
    "f": 0.2,
    "c": 3.9,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda",
    "aliases": ["помидоры", "помидоры свежие", "томат", "томаты свежие"]
  },
  {
    "n": 336,
    "key": "egg_raw",
    "name": "Яйцо сырое",
    "cat": "eggs",
    "form": "RAW",
    "unit": "g",
    "cal": 143,
    "p": 12.6,
    "f": 9.5,
    "c": 0.7,
    "allergen": "eggs",
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "aliases": ["яйцо", "яйца", "яйцо небольшое"]
  },
  {
    "n": 337,
    "key": "chicken_breast_raw",
    "name": "Куриная грудка сырая",
    "cat": "meat_poultry",
    "form": "RAW",
    "unit": "g",
    "cal": 120,
    "p": 22.5,
    "f": 2.6,
    "c": 0,
    "role": "MAIN_PROTEIN",
    "review": true,
    "src": "usda",
    "aliases": ["куриная грудка", "филе куриной грудки", "куриное филе"]
  },
  {
    "n": 338,
    "key": "round_rice_dry",
    "name": "Рис круглый сухой",
    "cat": "grains",
    "form": "DRY",
    "unit": "g",
    "cal": 360,
    "p": 7.1,
    "f": 0.7,
    "c": 79.2,
    "role": "STARCH",
    "vegan": true,
    "review": true,
    "src": "usda",
    "aliases": ["круглый рис", "рис круглый", "рис круглый непропаренный"]
  },
  {
    "n": 339,
    "key": "parmesan_hard",
    "name": "Пармезан",
    "cat": "dairy",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 392,
    "p": 35.8,
    "f": 25.8,
    "c": 3.2,
    "allergen": "milk",
    "role": "MAIN_PROTEIN",
    "veg": true,
    "review": true,
    "src": "usda",
    "aliases": ["тертый сыр пармезан", "тёртый сыр пармезан"]
  },
  {
    "n": 340,
    "key": "romaine_lettuce_raw",
    "name": "Салат ромен",
    "cat": "vegetables",
    "form": "RAW",
    "unit": "g",
    "cal": 17,
    "p": 1.2,
    "f": 0.3,
    "c": 3.3,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 341,
    "key": "iceberg_lettuce_raw",
    "name": "Салат Айсберг",
    "cat": "vegetables",
    "form": "RAW",
    "unit": "g",
    "cal": 14,
    "p": 0.9,
    "f": 0.1,
    "c": 3,
    "role": "VEGETABLE_BASE",
    "vegan": true,
    "review": true,
    "src": "usda"
  },
  {
    "n": 342,
    "key": "bread_crumbs_dry",
    "name": "Панировочные сухари",
    "cat": "technological_ingredients",
    "form": "DRY",
    "unit": "g",
    "cal": 395,
    "p": 13.4,
    "f": 5.3,
    "c": 71.3,
    "role": "BINDER",
    "review": true,
    "src": "usda"
  },
  {
    "n": 343,
    "key": "capers_pickled",
    "name": "Каперсы маринованные",
    "cat": "vegetables",
    "form": "READY_TO_EAT",
    "unit": "g",
    "cal": 23,
    "p": 2.4,
    "f": 0.9,
    "c": 4.9,
    "role": "SEASONING",
    "review": true,
    "src": "usda",
    "aliases": ["каперсы"]
  }
] as const;
