/**
 * CATALOG-V3-01C-A — Batch A NEW exercise content SoT.
 * Generated from WORKOUT-CATALOG-V3-SCOPE-01/04_TARGET_CATALOG_V3.csv (status=ADD).
 * Regenerator: node apps/api/scripts/generate-catalog-v3-01c-a-content.mjs
 * Do not invent UNKNOWN readiness / Energy / Timing / Media.
 */
import type { V3EquipmentGroupDraft, V3MuscleInvolvementDraft } from './catalog-v3-taxonomy';

export const CATALOG_V3_01C_A_VERSION = 'workout-catalog-v3-01c-a.1' as const;
export const CATALOG_V3_01C_A_CREATED_BY = 'system:catalog-v3-01c-a' as const;
export const CATALOG_V3_01C_A_ADVISORY_LOCK_KEY = 219_01_003;
export const CATALOG_V3_01C_A_EXPECTED_COUNT = 40 as const;

export const V3_01C_A_DIFFICULTIES = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'] as const;
export type V301cADifficulty = (typeof V3_01C_A_DIFFICULTIES)[number];

export type V301cAHeldEntry = {
  exerciseKey: string;
  reason: string;
};

export type V301cAContentEntry = {
  exerciseKey: string;
  nameRu: string;
  nameEn: string;
  familySlug: string;
  familyNameRu: string;
  familyNameEn: string;
  primaryMovementPattern: string;
  trainingRole: string;
  difficulty: V301cADifficulty;
  progressionGroup: string;
  generatorMovementPattern: string;
  repetitionMode: 'REPS' | 'DURATION';
  supportedPlaces: readonly string[];
  muscles: readonly V3MuscleInvolvementDraft[];
  equipmentGroups: readonly V3EquipmentGroupDraft[];
  techniqueRu: string;
  commonMistakeRu: string;
  easierVariantRu: string;
  harderVariantRu: string;
  breathingRu: string;
  stopConditionsRu: string;
  defaultSets: number | null;
  defaultRepsMin: number | null;
  defaultRepsMax: number | null;
  defaultDurationSeconds: number | null;
  defaultRestSeconds: number;
  estimatedDurationSeconds: number;
  estimatedMinutes: number;
  riskLevel: string;
  beginnerAllowed: boolean;
};

export const CATALOG_V3_01C_A_HELD: readonly V301cAHeldEntry[] = [
  { exerciseKey: "front_squat_goblet_to_barbell", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: dual implement (DB/barbell) encoded as one key" },
  { exerciseKey: "leg_press_narrow", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: micro-variant of existing machine_leg_press" },
  { exerciseKey: "meadows_row", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: obscure specialty row; defer to later batch" },
  { exerciseKey: "hip_airplane", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: advanced niche balance drill" },
  { exerciseKey: "copenhagen_adductor_regression", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: specialized rehab-style progression" },
  { exerciseKey: "inverted_row", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: equipment OR uses BAR_RACK not in V3 vocab" },
  { exerciseKey: "y_raise_prone", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: LIGHT_DUMBBELL not in V3 equipment vocab" },
  { exerciseKey: "nordic_hamstring_regression", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: advanced niche; needs clearer regression identity" },
  { exerciseKey: "smith_squat", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: machine micro-variant of barbell squat family" },
  { exerciseKey: "tibialis_raise", reason: "BATCH_A_HELD_FOR_IDENTITY_REVIEW: low-priority accessory; deferred for coverage balance" }
];

export const CATALOG_V3_01C_A_CONTENT: readonly V301cAContentEntry[] = [
  {
    exerciseKey: "dumbbell_bench_press",
    nameRu: "Жим гантелей лёжа",
    nameEn: "Dumbbell bench press",
    familySlug: "dumbbell",
    familyNameRu: "Жим гантелей лёжа",
    familyNameEn: "Dumbbell bench press",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "dumbbell",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"TRICEPS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"FRONT_DELTS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0},{"equipmentCode":"BENCH","sortOrder":1}]}],
    techniqueRu: "Лягте на скамью, гантели над грудью на прямых руках; опустите к сторонам груди и выжмите вверх, не прогибая поясницу.",
    commonMistakeRu: "Разводить локти слишком широко и отрывать таз от скамьи.",
    easierVariantRu: "Выполняйте жим гантелей на полу с меньшей амплитудой.",
    harderVariantRu: "Увеличьте паузу в нижней точке на 1–2 секунды.",
    breathingRu: "Вдох при опускании, выдох при жиме вверх.",
    stopConditionsRu: "Остановитесь при острой боли в плече или груди.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "chest_press_dumbbell_incline",
    nameRu: "Жим гантелей на наклонной",
    nameEn: "Incline DB press",
    familySlug: "chest",
    familyNameRu: "Жим гантелей на наклонной",
    familyNameEn: "Incline DB press",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "chest",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FRONT_DELTS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"TRICEPS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0},{"equipmentCode":"BENCH","sortOrder":1}]}],
    techniqueRu: "Сядьте на наклонную скамью, гантели над верхней частью груди; опустите к плечам и выжмите вверх по дуге.",
    commonMistakeRu: "Сильно прогибать поясницу и разводить локти до ушей.",
    easierVariantRu: "Уменьшите угол наклона скамьи.",
    harderVariantRu: "Добавьте медленный негатив 3 секунды.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в передней части плеча.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "dumbbell_fly",
    nameRu: "Разведения гантелей лёжа",
    nameEn: "Dumbbell fly",
    familySlug: "dumbbell",
    familyNameRu: "Разведения гантелей лёжа",
    familyNameEn: "Dumbbell fly",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "ISOLATION",
    difficulty: "INTERMEDIATE",
    progressionGroup: "dumbbell",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0},{"equipmentCode":"BENCH","sortOrder":1}]}],
    techniqueRu: "Лёжа на скамье, гантели над грудью слегка согнутыми локтями; разведите руки в стороны по дуге и сведите обратно.",
    commonMistakeRu: "Сгибать локти как в жиме или опускать слишком глубоко.",
    easierVariantRu: "Сократите амплитуду и используйте меньший вес.",
    harderVariantRu: "Задержите растяжение внизу на секунду.",
    breathingRu: "Вдох при разведении, выдох при сведении.",
    stopConditionsRu: "Остановитесь при резкой боли в плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "cable_fly",
    nameRu: "Сведения в кроссовере",
    nameEn: "Cable fly",
    familySlug: "cable",
    familyNameRu: "Сведения в кроссовере",
    familyNameEn: "Cable fly",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "ISOLATION",
    difficulty: "INTERMEDIATE",
    progressionGroup: "cable",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FRONT_DELTS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Встаньте между блоками, руки слегка согнуты; сведите рукояти перед грудью по дуге и контролируемо верните.",
    commonMistakeRu: "Тянуть руками за счёт сгибания локтей вместо дуги в плече.",
    easierVariantRu: "Установите блоки выше и сократите амплитуду.",
    harderVariantRu: "Сведите рукояти с паузой в центре.",
    breathingRu: "Выдох при сведении, вдох при возврате.",
    stopConditionsRu: "Остановитесь при дискомфорте в плечевом суставе.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "wall_push_up",
    nameRu: "Отжимания от стены",
    nameEn: "Wall push-up",
    familySlug: "wall",
    familyNameRu: "Отжимания от стены",
    familyNameEn: "Wall push-up",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "wall",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"TRICEPS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Упритесь ладонями в стену на уровне груди, тело прямой линией; согните локти, приблизьте грудь к стене и отожмитесь.",
    commonMistakeRu: "Прогибать поясницу и «ронять» бёдра к стене.",
    easierVariantRu: "Поставьте ноги ближе к стене.",
    harderVariantRu: "Отойдите дальше от стены, увеличив наклон.",
    breathingRu: "Вдох к стене, выдох от стены.",
    stopConditionsRu: "Остановитесь при боли в запястье или плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "push_up_decline",
    nameRu: "Отжимания с ногами на возвышении",
    nameEn: "Decline push-up",
    familySlug: "push",
    familyNameRu: "Отжимания с ногами на возвышении",
    familyNameEn: "Decline push-up",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "push",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"TRICEPS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"FRONT_DELTS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0},{"equipmentCode":"BOX_STEP","sortOrder":1}]}],
    techniqueRu: "Носки на устойчивой возвышенности, ладони на полу под плечами; опустите грудь между руками и отожмитесь цельной линией.",
    commonMistakeRu: "Проваливать поясницу и поднимать таз.",
    easierVariantRu: "Используйте более низкую опору для ног.",
    harderVariantRu: "Замедлите негатив до 3 секунд.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в плече или запястье.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "close_grip_push_up",
    nameRu: "Алмазные отжимания",
    nameEn: "Close-grip push-up",
    familySlug: "close",
    familyNameRu: "Алмазные отжимания",
    familyNameEn: "Close-grip push-up",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "close",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"TRICEPS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"CHEST","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Ладони уже плеч, тело прямой линией; опуститесь, держа локти ближе к корпусу, и отожмитесь.",
    commonMistakeRu: "Разводить локти в стороны как в широких отжиманиях.",
    easierVariantRu: "Выполняйте с колен с узкой постановкой рук.",
    harderVariantRu: "Добавьте паузу внизу.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в локте или запястье.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "pull_up",
    nameRu: "Подтягивания",
    nameEn: "Pull-up",
    familySlug: "pull",
    familyNameRu: "Подтягивания",
    familyNameEn: "Pull-up",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "MAIN",
    difficulty: "ADVANCED",
    progressionGroup: "pull",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"BICEPS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"PULL_UP_BAR","sortOrder":0}]}],
    techniqueRu: "Повисните прямым хватом чуть шире плеч; подтяните грудь к перекладине, сводя лопатки, и опуститесь под контролем.",
    commonMistakeRu: "Раскачиваться корпусом и не разгибать руки внизу.",
    easierVariantRu: "Используйте резиновую петлю или негативные подтягивания.",
    harderVariantRu: "Добавьте паузу вверху у перекладины.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при острой боли в локте или плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "chin_up",
    nameRu: "Подтягивания обратным хватом",
    nameEn: "Chin-up",
    familySlug: "chin",
    familyNameRu: "Подтягивания обратным хватом",
    familyNameEn: "Chin-up",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "MAIN",
    difficulty: "ADVANCED",
    progressionGroup: "chin",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"BICEPS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"PULL_UP_BAR","sortOrder":0}]}],
    techniqueRu: "Повисните обратным хватом на ширине плеч; подтянитесь, направляя грудь к перекладине, и плавно опуститесь.",
    commonMistakeRu: "Сильно отклонять корпус назад и сокращать амплитуду.",
    easierVariantRu: "Используйте ленту-ассист или негативы.",
    harderVariantRu: "Замедлите опускание до 3–4 секунд.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в локте или бицепсе.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "lat_pulldown_wide",
    nameRu: "Тяга верхнего блока широким хватом",
    nameEn: "Wide-grip lat pulldown",
    familySlug: "lat",
    familyNameRu: "Тяга верхнего блока широким хватом",
    familyNameEn: "Wide-grip lat pulldown",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "lat",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"BICEPS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"LAT_PULLDOWN","sortOrder":0}]}],
    techniqueRu: "Сядьте в тренажёр, возьмите рукоять широко; тяните к верхней груди, сводя лопатки вниз-назад, затем отпустите вверх.",
    commonMistakeRu: "Тянуть рукоять за голову и сильно отклоняться назад.",
    easierVariantRu: "Уменьшите вес и используйте нейтральный хват.",
    harderVariantRu: "Пауза 1 секунда у груди.",
    breathingRu: "Выдох при тяге, вдох при возврате.",
    stopConditionsRu: "Остановитесь при боли в плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "seated_row_machine",
    nameRu: "Тяга горизонтального блока/тренажёра",
    nameEn: "Seated row machine",
    familySlug: "seated",
    familyNameRu: "Тяга горизонтального блока/тренажёра",
    familyNameEn: "Seated row machine",
    primaryMovementPattern: "HORIZONTAL_PULL",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "seated",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"BICEPS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"ROW_MACHINE","sortOrder":0}]}],
    techniqueRu: "Сядьте с упором груди/ног по конструкции тренажёра; тяните рукоять к животу, сводя лопатки, и медленно верните.",
    commonMistakeRu: "Округлять спину и дергать вес корпусом.",
    easierVariantRu: "Снизьте вес и сократите амплитуду.",
    harderVariantRu: "Добавьте паузу в сокращении.",
    breathingRu: "Выдох на тяге, вдох на возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "face_pull_cable",
    nameRu: "Тяга к лицу в кроссовере",
    nameEn: "Cable face pull",
    familySlug: "face",
    familyNameRu: "Тяга к лицу в кроссовере",
    familyNameEn: "Cable face pull",
    primaryMovementPattern: "HORIZONTAL_PULL",
    trainingRole: "ACCESSORY",
    difficulty: "BEGINNER",
    progressionGroup: "face",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"REAR_DELTS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"TRAPS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Поставьте блок на уровень лица; тяните канат к лицу, разводя руки и направляя локти назад-в стороны.",
    commonMistakeRu: "Тянуть только бицепсом без внешней ротации плеч.",
    easierVariantRu: "Используйте меньший вес и шагните ближе.",
    harderVariantRu: "Удерживайте конечную точку 1–2 секунды.",
    breathingRu: "Выдох на тяге, вдох на возврате.",
    stopConditionsRu: "Остановитесь при щелчках/боли в плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "straight_arm_pulldown",
    nameRu: "Тяга прямой рукой",
    nameEn: "Straight-arm pulldown",
    familySlug: "straight",
    familyNameRu: "Тяга прямой рукой",
    familyNameEn: "Straight-arm pulldown",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "ISOLATION",
    difficulty: "INTERMEDIATE",
    progressionGroup: "straight",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Встаньте перед верхним блоком, руки почти прямые; тяните рукоять дугой к бёдрам за счёт широчайших и медленно верните.",
    commonMistakeRu: "Сильно сгибать локти, превращая движение в обычную тягу.",
    easierVariantRu: "Сократите амплитуду и уменьшите вес.",
    harderVariantRu: "Пауза у бёдер внизу.",
    breathingRu: "Выдох вниз, вдох вверх.",
    stopConditionsRu: "Остановитесь при боли в пояснице или плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "single_arm_cable_row",
    nameRu: "Тяга одной рукой в кроссовере",
    nameEn: "Single-arm cable row",
    familySlug: "single",
    familyNameRu: "Тяга одной рукой в кроссовере",
    familyNameEn: "Single-arm cable row",
    primaryMovementPattern: "HORIZONTAL_PULL",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "single",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"BICEPS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Встаньте боком к блоку, свободная рука на опоре; тяните рукоять к поясу, локоть вдоль корпуса, затем отпустите.",
    commonMistakeRu: "Разворачивать весь корпус вместо работы лопатки.",
    easierVariantRu: "Сядьте и выполняйте с упором.",
    harderVariantRu: "Добавьте паузу у корпуса.",
    breathingRu: "Выдох на тяге, вдох на возврате.",
    stopConditionsRu: "Остановитесь при боли в плече или пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "rear_delt_fly_dumbbell",
    nameRu: "Разведения на заднюю дельту",
    nameEn: "Rear delt fly",
    familySlug: "rear",
    familyNameRu: "Разведения на заднюю дельту",
    familyNameEn: "Rear delt fly",
    primaryMovementPattern: "HORIZONTAL_PULL",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "rear",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"REAR_DELTS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Наклонитесь с прямой спиной, гантели под плечами; разведите руки в стороны до линии корпуса, локти мягкие.",
    commonMistakeRu: "Поднимать вес рывком трапециями вверх к ушам.",
    easierVariantRu: "Опереться грудью о наклонную скамью.",
    harderVariantRu: "Замедлите негатив.",
    breathingRu: "Выдох на разведении, вдох на опускании.",
    stopConditionsRu: "Остановитесь при боли в шее или плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "arnold_press_dumbbell",
    nameRu: "Жим Арнольда",
    nameEn: "Arnold press",
    familySlug: "arnold",
    familyNameRu: "Жим Арнольда",
    familyNameEn: "Arnold press",
    primaryMovementPattern: "VERTICAL_PUSH",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "arnold",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"FRONT_DELTS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"SIDE_DELTS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"TRICEPS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Сидя или стоя, гантели перед плечами ладонями к себе; разворачивая запястья наружу, выжмите вверх и верните обратно.",
    commonMistakeRu: "Прогибать поясницу и ударять гантели друг о друга вверху.",
    easierVariantRu: "Жмите сидя с опорой спины без полного разворота.",
    harderVariantRu: "Выполняйте стоя с более медленным темпом.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "dumbbell_bicep_curl",
    nameRu: "Сгибания на бицепс с гантелями",
    nameEn: "Dumbbell biceps curl",
    familySlug: "dumbbell",
    familyNameRu: "Сгибания на бицепс с гантелями",
    familyNameEn: "Dumbbell biceps curl",
    primaryMovementPattern: "ELBOW_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "dumbbell",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"BICEPS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FOREARMS_GRIP","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Встаньте, гантели у бёдер; сгибайте локти, поднимая вес к плечам без раскачки корпуса, и опустите под контролем.",
    commonMistakeRu: "Забрасывать гантели за счёт наклона назад.",
    easierVariantRu: "Выполняйте поочерёдно с меньшей амплитудой.",
    harderVariantRu: "Добавьте паузу вверху.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "hammer_curl_dumbbell",
    nameRu: "Молотковые сгибания",
    nameEn: "Hammer curl",
    familySlug: "hammer",
    familyNameRu: "Молотковые сгибания",
    familyNameEn: "Hammer curl",
    primaryMovementPattern: "ELBOW_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "hammer",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"BICEPS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FOREARMS_GRIP","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Держите гантели нейтральным хватом; сгибайте локти, сохраняя кисти «молотом», без раскачки туловища.",
    commonMistakeRu: "Разворачивать кисти и помогать корпусом.",
    easierVariantRu: "Сгибайте руки поочерёдно.",
    harderVariantRu: "Замедлите опускание.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в предплечье или локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "triceps_pushdown",
    nameRu: "Разгибания на трицепс на блоке",
    nameEn: "Triceps pushdown",
    familySlug: "triceps",
    familyNameRu: "Разгибания на трицепс на блоке",
    familyNameEn: "Triceps pushdown",
    primaryMovementPattern: "ELBOW_EXTENSION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "triceps",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"TRICEPS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Встаньте у верхнего блока, локти прижаты к корпусу; разогните руки вниз до полного выпрямления и плавно верните.",
    commonMistakeRu: "Отводить локти вперёд и наклоняться всем телом на вес.",
    easierVariantRu: "Используйте канат и меньший вес.",
    harderVariantRu: "Пауза внизу при разогнутых руках.",
    breathingRu: "Выдох вниз, вдох вверх.",
    stopConditionsRu: "Остановитесь при боли в локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "overhead_triceps_extension_dumbbell",
    nameRu: "Французский жим гантели",
    nameEn: "DB overhead triceps extension",
    familySlug: "overhead",
    familyNameRu: "Французский жим гантели",
    familyNameEn: "DB overhead triceps extension",
    primaryMovementPattern: "ELBOW_EXTENSION",
    trainingRole: "ISOLATION",
    difficulty: "INTERMEDIATE",
    progressionGroup: "overhead",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"TRICEPS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Поднимите гантель над головой двумя руками; сгибая локти, опустите вес за голову и разогните руки вверх.",
    commonMistakeRu: "Раздвигать локти в стороны и прогибать поясницу.",
    easierVariantRu: "Выполняйте сидя с опорой спины.",
    harderVariantRu: "Используйте одну гантель на руку поочерёдно.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в локте или плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "barbell_back_squat",
    nameRu: "Приседания со штангой на спине",
    nameEn: "Barbell back squat",
    familySlug: "barbell",
    familyNameRu: "Приседания со штангой на спине",
    familyNameEn: "Barbell back squat",
    primaryMovementPattern: "SQUAT",
    trainingRole: "MAIN",
    difficulty: "ADVANCED",
    progressionGroup: "barbell",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"LOWER_BACK","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BARBELL","sortOrder":0},{"equipmentCode":"SQUAT_RACK","sortOrder":1}]}],
    techniqueRu: "Штанга на верхней части спины, стопы на ширине плеч; отведите таз назад-вниз до комфортной глубины и встаньте, сохраняя опору на всей стопе.",
    commonMistakeRu: "Заваливать колени внутрь и округлять поясницу.",
    easierVariantRu: "Приседайте до параллели с меньшей нагрузкой в раме.",
    harderVariantRu: "Увеличьте паузу внизу.",
    breathingRu: "Вдох на опускании, выдох на подъёме.",
    stopConditionsRu: "Остановитесь при острой боли в колене или пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "bulgarian_split_squat",
    nameRu: "Болгарские сплит-приседания",
    nameEn: "Bulgarian split squat",
    familySlug: "bulgarian",
    familyNameRu: "Болгарские сплит-приседания",
    familyNameEn: "Bulgarian split squat",
    primaryMovementPattern: "LUNGE",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "bulgarian",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]},{"groupKind":"OPTIONAL","sortOrder":1,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]},{"groupKind":"OPTIONAL","sortOrder":2,"items":[{"equipmentCode":"BENCH","sortOrder":0}]}],
    techniqueRu: "Задняя стопа на скамье/опоре, передняя впереди; опуститесь сгибанием переднего колена и встаньте, корпус почти вертикален.",
    commonMistakeRu: "Ставить переднюю стопу слишком близко и заваливать колено внутрь.",
    easierVariantRu: "Уменьшите глубину или выполняйте без отягощения.",
    harderVariantRu: "Держите гантели в руках.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в колене или сгибателе бедра.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "walking_lunge_bodyweight",
    nameRu: "Выпады в движении",
    nameEn: "Walking lunge",
    familySlug: "walking",
    familyNameRu: "Выпады в движении",
    familyNameEn: "Walking lunge",
    primaryMovementPattern: "LUNGE",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "walking",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Шагните вперёд, опустите заднее колено к полу под контролем; оттолкнитесь передней ногой и шагайте в следующий выпад.",
    commonMistakeRu: "Падать коленом внутрь и наклоняться чрезмерно вперёд.",
    easierVariantRu: "Делайте выпады на месте с опорой рукой.",
    harderVariantRu: "Увеличьте длину шага и глубину.",
    breathingRu: "Вдох вниз, выдох при шаге вверх.",
    stopConditionsRu: "Остановитесь при боли в колене.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "kettlebell_goblet_squat",
    nameRu: "Гоблет-приседания с гирей",
    nameEn: "KB goblet squat",
    familySlug: "kettlebell",
    familyNameRu: "Гоблет-приседания с гирей",
    familyNameEn: "KB goblet squat",
    primaryMovementPattern: "SQUAT",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "kettlebell",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"KETTLEBELL","sortOrder":0}]}],
    techniqueRu: "Держите гирю у груди за рога/корпус; присядьте, разводя колени по носкам, и встаньте, сохраняя корпус вертикальным.",
    commonMistakeRu: "Округлять спину и отрывать пятки.",
    easierVariantRu: "Приседайте до удобной глубины без гири у груди (руки перед собой).",
    harderVariantRu: "Добавьте паузу внизу.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в коленях или пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "sumo_squat_dumbbell",
    nameRu: "Приседания сумо с гантелью",
    nameEn: "DB sumo squat",
    familySlug: "sumo",
    familyNameRu: "Приседания сумо с гантелью",
    familyNameEn: "DB sumo squat",
    primaryMovementPattern: "SQUAT",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "sumo",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"GLUTES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"QUADS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"ADDUCTORS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Широкая постановка стоп носками наружу, гантель между ног; присядьте, сохраняя грудь вверх, и встаньте, сжимая ягодицы.",
    commonMistakeRu: "Заваливать колени внутрь и округлять поясницу.",
    easierVariantRu: "Уменьшите ширину стойки и вес.",
    harderVariantRu: "Углубите присед с паузой.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли во внутренней стороне бедра или колене.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "conventional_deadlift",
    nameRu: "Становая тяга классическая",
    nameEn: "Conventional deadlift",
    familySlug: "conventional",
    familyNameRu: "Становая тяга классическая",
    familyNameEn: "Conventional deadlift",
    primaryMovementPattern: "HINGE",
    trainingRole: "MAIN",
    difficulty: "ADVANCED",
    progressionGroup: "conventional",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"HAMSTRINGS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":2},{"muscleCode":"FOREARMS_GRIP","involvement":"SECONDARY","sortOrder":3}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BARBELL","sortOrder":0}]}],
    techniqueRu: "Штанга над серединой стопы, хват снаружи ног; поднимите вес разгибанием ног и корпуса до вертикали, затем опустите по той же траектории.",
    commonMistakeRu: "Округлять поясницу и рано выпрямлять ноги, оставляя гриф далеко.",
    easierVariantRu: "Тяните с плинтов/блоков или используйте гирю.",
    harderVariantRu: "Добавьте паузу ниже колена на подъёме.",
    breathingRu: "Вдох перед съёмом, выдох вверху или при опускании по технике.",
    stopConditionsRu: "Остановитесь при острой боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "romanian_deadlift_kettlebell",
    nameRu: "Румынская тяга с гирей",
    nameEn: "KB Romanian deadlift",
    familySlug: "romanian",
    familyNameRu: "Румынская тяга с гирей",
    familyNameEn: "KB Romanian deadlift",
    primaryMovementPattern: "HINGE",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "romanian",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"HAMSTRINGS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"KETTLEBELL","sortOrder":0}]}],
    techniqueRu: "Встаньте с гирей перед собой; отводите таз назад, скользя гирей вдоль ног с мягкими коленями, затем вернитесь, сжав ягодицы.",
    commonMistakeRu: "Сильно сгибать колени в присед и округлять спину.",
    easierVariantRu: "Сократите амплитуду до середины голени.",
    harderVariantRu: "Замедлите негатив.",
    breathingRu: "Вдох при наклоне, выдох при подъёме.",
    stopConditionsRu: "Остановитесь при боли в пояснице или задней поверхности бедра.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "kettlebell_deadlift",
    nameRu: "Становая с гирей",
    nameEn: "KB deadlift",
    familySlug: "kettlebell",
    familyNameRu: "Становая с гирей",
    familyNameEn: "KB deadlift",
    primaryMovementPattern: "HINGE",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "kettlebell",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"HAMSTRINGS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"KETTLEBELL","sortOrder":0}]}],
    techniqueRu: "Гиря между стоп; возьмитесь за дужку, выпрямите спину и встаньте за счёт ног и таза, затем опустите гирю на пол.",
    commonMistakeRu: "Тянуть спиной с округлённой поясницей.",
    easierVariantRu: "Поставьте гирю на небольшую возвышенность.",
    harderVariantRu: "Используйте более тяжёлую гирю с паузой у пола.",
    breathingRu: "Вдох перед съёмом, выдох вверху.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "kettlebell_swing",
    nameRu: "Махи гирей",
    nameEn: "Kettlebell swing",
    familySlug: "kettlebell",
    familyNameRu: "Махи гирей",
    familyNameEn: "Kettlebell swing",
    primaryMovementPattern: "HINGE",
    trainingRole: "CONDITIONING",
    difficulty: "INTERMEDIATE",
    progressionGroup: "kettlebell",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"GLUTES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HAMSTRINGS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"KETTLEBELL","sortOrder":0}]}],
    techniqueRu: "Хип-хинджем отведите гирю назад между ног и резко разогните таз, вынося гирю до уровня груди; руки остаются «верёвками».",
    commonMistakeRu: "Приседать слишком глубоко и поднимать гирю руками.",
    easierVariantRu: "Делайте махи до уровня пояса с лёгкой гирей.",
    harderVariantRu: "Увеличьте мощность разгибания таза до уровня плеч.",
    breathingRu: "Выдох на разгибании таза, вдох на возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице или потери контроля гири.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "leg_curl_lying",
    nameRu: "Сгибания ног лёжа",
    nameEn: "Lying leg curl",
    familySlug: "leg",
    familyNameRu: "Сгибания ног лёжа",
    familyNameEn: "Lying leg curl",
    primaryMovementPattern: "KNEE_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "leg",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"HAMSTRINGS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"LEG_CURL_MACHINE","sortOrder":0}]}],
    techniqueRu: "Лягте в тренажёр, валик на нижней части голени; сгибайте ноги к ягодицам и медленно разгибайте.",
    commonMistakeRu: "Отрывать таз от подушки и помогать рывком.",
    easierVariantRu: "Уменьшите вес и амплитуду.",
    harderVariantRu: "Пауза в сокращении.",
    breathingRu: "Выдох на сгибании, вдох на разгибании.",
    stopConditionsRu: "Остановитесь при боли в колене или задней поверхности бедра.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "cable_kickback",
    nameRu: "Отведения ноги назад на блоке",
    nameEn: "Cable glute kickback",
    familySlug: "cable",
    familyNameRu: "Отведения ноги назад на блоке",
    familyNameEn: "Cable glute kickback",
    primaryMovementPattern: "HIP_EXTENSION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "cable",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"GLUTES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HAMSTRINGS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Прикрепите манжету к нижнему блоку; отведите ногу назад, сохраняя корпус стабильным, и медленно верните.",
    commonMistakeRu: "Прогибать поясницу и разворачивать таз.",
    easierVariantRu: "Уменьшите амплитуду и вес.",
    harderVariantRu: "Пауза в верхней точке.",
    breathingRu: "Выдох при отведении, вдох при возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "single_leg_glute_bridge",
    nameRu: "Ягодичный мост на одной ноге",
    nameEn: "Single-leg glute bridge",
    familySlug: "single",
    familyNameRu: "Ягодичный мост на одной ноге",
    familyNameEn: "Single-leg glute bridge",
    primaryMovementPattern: "HIP_EXTENSION",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "single",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"GLUTES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HAMSTRINGS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Лёжа на спине, одна стопа на полу, другая выпрямлена; поднимите таз, сжимая ягодицу опорной ноги, и опустите.",
    commonMistakeRu: "Прогибать поясницу и вращать таз в сторону.",
    easierVariantRu: "Держите вторую ногу согнутой в воздухе.",
    harderVariantRu: "Добавьте паузу вверху.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "hanging_knee_raise",
    nameRu: "Подъёмы коленей в висе",
    nameEn: "Hanging knee raise",
    familySlug: "hanging",
    familyNameRu: "Подъёмы коленей в висе",
    familyNameEn: "Hanging knee raise",
    primaryMovementPattern: "CORE_FLEXION",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "hanging",
    generatorMovementPattern: "core",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"ABS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HIP_FLEXORS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"PULL_UP_BAR","sortOrder":0}]}],
    techniqueRu: "Повисните на перекладине; подтяните колени к груди, не раскачиваясь, и медленно опустите.",
    commonMistakeRu: "Раскачиваться махом и помогать только бёдрами без контроля пресса.",
    easierVariantRu: "Выполняйте подъёмы коленей лёжа или в упоре на брусьях с поддержкой.",
    harderVariantRu: "Выпрямляйте ноги в подъёме носков к перекладине.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в пояснице или хвате.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "cable_crunch",
    nameRu: "Скручивания на блоке",
    nameEn: "Cable crunch",
    familySlug: "cable",
    familyNameRu: "Скручивания на блоке",
    familyNameEn: "Cable crunch",
    primaryMovementPattern: "CORE_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "cable",
    generatorMovementPattern: "core",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"ABS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Встаньте на колени у верхнего блока, рукоять у головы; скрутите корпус вниз, округляя грудной отдел, и вернитесь.",
    commonMistakeRu: "Тянуть руками и сгибать только тазобедренный сустав.",
    easierVariantRu: "Уменьшите вес и амплитуду.",
    harderVariantRu: "Пауза внизу в сжатии.",
    breathingRu: "Выдох при скручивании, вдох при подъёме.",
    stopConditionsRu: "Остановитесь при боли в шее или пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "ab_wheel_regression",
    nameRu: "Ролик для пресса (регрессия с колен)",
    nameEn: "Ab wheel regression",
    familySlug: "ab",
    familyNameRu: "Ролик для пресса (регрессия с колен)",
    familyNameEn: "Ab wheel regression",
    primaryMovementPattern: "CORE_ANTI_EXTENSION",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "ab",
    generatorMovementPattern: "core",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"ABS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"DEEP_CORE","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"AB_WHEEL","sortOrder":0},{"equipmentCode":"MAT","sortOrder":1}]}],
    techniqueRu: "С колен возьмите ролик; прокатите его вперёд, сохраняя нейтральную поясницу, и верните к коленям.",
    commonMistakeRu: "Проваливать поясницу и «падать» плечами вниз.",
    easierVariantRu: "Сократите выкат до короткой дистанции.",
    harderVariantRu: "Увеличьте дистанцию выката.",
    breathingRu: "Вдох наружу, выдох на возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "cable_woodchop",
    nameRu: "Рубка дров на блоке",
    nameEn: "Cable woodchop",
    familySlug: "cable",
    familyNameRu: "Рубка дров на блоке",
    familyNameEn: "Cable woodchop",
    primaryMovementPattern: "CORE_ROTATION",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "cable",
    generatorMovementPattern: "core",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"OBLIQUES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Поставьте блок высоко сбоку; тяните рукоять диагонально вниз-через корпус к противоположному бедру с поворотом туловища.",
    commonMistakeRu: "Крутить только руками без участия корпуса.",
    easierVariantRu: "Уменьшите вес и амплитуду поворота.",
    harderVariantRu: "Выполняйте из более высокого блока с паузой внизу.",
    breathingRu: "Выдох на рубке, вдох на возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "farmer_carry_kettlebell",
    nameRu: "Прогулка фермера с гирями",
    nameEn: "KB farmer carry",
    familySlug: "farmer",
    familyNameRu: "Прогулка фермера с гирями",
    familyNameEn: "KB farmer carry",
    primaryMovementPattern: "CARRY",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "farmer",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"FOREARMS_GRIP","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"TRAPS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"KETTLEBELL","sortOrder":0}]}],
    techniqueRu: "Возьмите гири по бокам, встаньте высоко; идите короткими шагами, сохраняя корпус жёстким и плечи опущенными.",
    commonMistakeRu: "Сутулиться и раскачиваться в стороны.",
    easierVariantRu: "Несите одну гирю легче на короткую дистанцию.",
    harderVariantRu: "Увеличьте вес или дистанцию.",
    breathingRu: "Дышите ровно, не задерживая дыхание надолго.",
    stopConditionsRu: "Остановитесь при потере хвата или боли в пояснице.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "step_up_bodyweight",
    nameRu: "Шаги на тумбу (без отягощения)",
    nameEn: "Bodyweight step-up",
    familySlug: "step",
    familyNameRu: "Шаги на тумбу (без отягощения)",
    familyNameEn: "Bodyweight step-up",
    primaryMovementPattern: "LUNGE",
    trainingRole: "MAIN",
    difficulty: "BEGINNER",
    progressionGroup: "step",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BOX_STEP","sortOrder":0}]}],
    techniqueRu: "Поставьте всю стопу на тумбу; встаньте на неё ведущей ногой без толчка задней и контролируемо шагните вниз.",
    commonMistakeRu: "Отталкиваться задней ногой и заваливать колено внутрь.",
    easierVariantRu: "Используйте более низкую тумбу.",
    harderVariantRu: "Замедлите спуск с тумбы.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в колене.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "band_bicep_curl",
    nameRu: "Сгибания на бицепс с лентой",
    nameEn: "Band biceps curl",
    familySlug: "band",
    familyNameRu: "Сгибания на бицепс с лентой",
    familyNameEn: "Band biceps curl",
    primaryMovementPattern: "ELBOW_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "band",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"BICEPS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"RESISTANCE_BAND","sortOrder":0}]}],
    techniqueRu: "Встаньте на ленту, рукояти в руках; сгибайте локти к плечам, прижимая локти к корпусу, и медленно разогните.",
    commonMistakeRu: "Помогать раскачкой корпуса.",
    easierVariantRu: "Возьмите более лёгкую ленту.",
    harderVariantRu: "Сделайте паузу вверху.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "band_triceps_extension",
    nameRu: "Разгибания на трицепс с лентой",
    nameEn: "Band triceps extension",
    familySlug: "band",
    familyNameRu: "Разгибания на трицепс с лентой",
    familyNameEn: "Band triceps extension",
    primaryMovementPattern: "ELBOW_EXTENSION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "band",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"TRICEPS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"RESISTANCE_BAND","sortOrder":0}]}],
    techniqueRu: "Закрепите ленту сверху/перед собой; разогните руки в локтях, сохраняя плечи стабильными, и верните под контролем.",
    commonMistakeRu: "Раздвигать локти и помогать корпусом.",
    easierVariantRu: "Укоротите рычаг ленты (встаньте ближе к точке крепления).",
    harderVariantRu: "Пауза в разогнутом положении.",
    breathingRu: "Выдох при разгибании, вдох при сгибании.",
    stopConditionsRu: "Остановитесь при боли в локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  }
];
