/**
 * WORKOUT-CATALOG-01A вЂ” target catalog manifest (exactly 84).
 * Machine-readable source of inventory / acceptance. Canonical ru-RU content lives in canonical-content-01b.json (SoT).
 *
 * Generated helper may refresh this file; treat committed TS as SoT.
 */
import type {
  CatalogPlace,
  CatalogTrainingLevel,
  InitialCatalogStatus,
  LoadLevel,
  ManifestMovementPattern,
  PlannedContentPackage,
  RepetitionMode,
  WorkoutCatalogEquipment,
} from "./catalog-enums";
import { CATALOG_MANIFEST_VERSION } from "./catalog-enums";

export type CatalogManifestEntry = {
  ordinal: number;
  slug: string;
  familySlug: string;
  nameRu: string;
  nameEn: string;
  minLevel: CatalogTrainingLevel;
  supportedPlaces: CatalogPlace[];
  requiredEquipment: WorkoutCatalogEquipment[];
  optionalEquipment: WorkoutCatalogEquipment[];
  movementPattern: ManifestMovementPattern;
  primaryMuscleGroups: string[];
  secondaryMuscleGroups: string[];
  repetitionMode: RepetitionMode;
  impactLevel: LoadLevel;
  balanceRequirement: LoadLevel;
  floorRequired: boolean;
  overheadMovement: boolean;
  deepKneeFlexion: boolean;
  singleLeg: boolean;
  beginnerAllowed: boolean;
  initialCatalogStatus: InitialCatalogStatus;
  plannedContentPackage: PlannedContentPackage;
  /** Explicit legacy Exercise.key mapping; never fuzzy-matched. */
  legacyExerciseKey: string | null;
};

export const WORKOUT_CATALOG_MANIFEST_VERSION = CATALOG_MANIFEST_VERSION;

export const WORKOUT_CATALOG_MANIFEST = [
  {
    ordinal: 1,
    slug: "morning_walk",
    familySlug: "outdoor_walk",
    nameRu: "РЈС‚СЂРµРЅРЅСЏСЏ С…РѕРґСЊР±Р°",
    nameEn: "Morning walk",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["NONE"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "morning_walk",
  },
  {
    ordinal: 2,
    slug: "bodyweight_squats",
    familySlug: "bodyweight_squat",
    nameRu: "РџСЂРёСЃРµРґР°РЅРёСЏ СЃ РІРµСЃРѕРј С‚РµР»Р°",
    nameEn: "Bodyweight squats",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "bodyweight_squats",
  },
  {
    ordinal: 3,
    slug: "stretching",
    familySlug: "gentle_stretch",
    nameRu: "Р Р°СЃС‚СЏР¶РєР°",
    nameEn: "Stretching",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "mobility",
    primaryMuscleGroups: ["mobility"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "stretching",
  },
  {
    ordinal: 4,
    slug: "light_jog",
    familySlug: "easy_jog",
    nameRu: "Р›С‘РіРєРёР№ Р±РµРі",
    nameEn: "Light jog",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["NONE"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "MODERATE",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "light_jog",
  },
  {
    ordinal: 5,
    slug: "core_plank",
    familySlug: "plank",
    nameRu: "РџР»Р°РЅРєР°",
    nameEn: "Core plank",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "anti_extension_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "core_plank",
  },
  {
    ordinal: 6,
    slug: "mobility_flow",
    familySlug: "mobility_flow",
    nameRu: "РљРѕРјРїР»РµРєСЃ РЅР° РїРѕРґРІРёР¶РЅРѕСЃС‚СЊ",
    nameEn: "Mobility flow",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "mobility",
    primaryMuscleGroups: ["mobility"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "mobility_flow",
  },
  {
    ordinal: 7,
    slug: "recovery_walk",
    familySlug: "outdoor_walk",
    nameRu: "Р’РѕСЃСЃС‚Р°РЅРѕРІРёС‚РµР»СЊРЅР°СЏ С…РѕРґСЊР±Р°",
    nameEn: "Recovery walk",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["NONE"],
    optionalEquipment: [],
    movementPattern: "recovery",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "recovery_walk",
  },
  {
    ordinal: 8,
    slug: "push_ups",
    familySlug: "push_up",
    nameRu: "РћС‚Р¶РёРјР°РЅРёСЏ",
    nameEn: "Push-ups",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: ["shoulders"],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "push_ups",
  },
  {
    ordinal: 9,
    slug: "glute_bridge",
    familySlug: "glute_bridge",
    nameRu: "РЇРіРѕРґРёС‡РЅС‹Р№ РјРѕСЃС‚",
    nameEn: "Glute bridge",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "hinge",
    primaryMuscleGroups: ["glutes", "hamstrings"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "glute_bridge",
  },
  {
    ordinal: 10,
    slug: "dead_bug",
    familySlug: "dead_bug",
    nameRu: "Р–СѓРє РЅР° СЃРїРёРЅРµ",
    nameEn: "Dead bug",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "anti_extension_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "dead_bug",
  },
  {
    ordinal: 11,
    slug: "band_row",
    familySlug: "band_row",
    nameRu: "РўСЏРіР° СЌСЃРїР°РЅРґРµСЂР°",
    nameEn: "Band row",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "band_row",
  },
  {
    ordinal: 12,
    slug: "band_pull_apart",
    familySlug: "band_pull_apart",
    nameRu: "Р Р°Р·РІРµРґРµРЅРёРµ СЌСЃРїР°РЅРґРµСЂР°",
    nameEn: "Band pull-apart",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["upper_back", "rear_delts"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "band_pull_apart",
  },
  {
    ordinal: 13,
    slug: "dumbbell_row",
    familySlug: "dumbbell_row",
    nameRu: "РўСЏРіР° РіР°РЅС‚РµР»Рё",
    nameEn: "Dumbbell row",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: ["BENCH"],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "dumbbell_row",
  },
  {
    ordinal: 14,
    slug: "goblet_squat",
    familySlug: "goblet_squat",
    nameRu: "РџСЂРёСЃРµРґР°РЅРёРµ СЃ РіР°РЅС‚РµР»СЊСЋ",
    nameEn: "Goblet squat",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "goblet_squat",
  },
  {
    ordinal: 15,
    slug: "machine_leg_press",
    familySlug: "leg_press",
    nameRu: "Р–РёРј РЅРѕРіР°РјРё РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Machine leg press",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "machine_leg_press",
  },
  {
    ordinal: 16,
    slug: "cable_row",
    familySlug: "cable_row",
    nameRu: "РўСЏРіР° РЅРёР¶РЅРµРіРѕ Р±Р»РѕРєР°",
    nameEn: "Cable row",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "cable_row",
  },
  {
    ordinal: 17,
    slug: "treadmill_walk",
    familySlug: "treadmill_walk",
    nameRu: "РҐРѕРґСЊР±Р° РЅР° РґРѕСЂРѕР¶РєРµ",
    nameEn: "Treadmill walk",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["CARDIO_MACHINE"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "treadmill_walk",
  },
  {
    ordinal: 18,
    slug: "chest_press_machine",
    familySlug: "chest_press_machine",
    nameRu: "Р–РёРј РѕС‚ РіСЂСѓРґРё РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Machine chest press",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "chest_press_machine",
  },
  {
    ordinal: 19,
    slug: "barbell_romanian_deadlift",
    familySlug: "romanian_deadlift",
    nameRu: "Р СѓРјС‹РЅСЃРєР°СЏ С‚СЏРіР° СЃРѕ С€С‚Р°РЅРіРѕР№",
    nameEn: "Barbell Romanian deadlift",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["BARBELL"],
    optionalEquipment: [],
    movementPattern: "hinge",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "barbell_romanian_deadlift",
  },
  {
    ordinal: 20,
    slug: "lat_pulldown",
    familySlug: "lat_pulldown",
    nameRu: "РўСЏРіР° РІРµСЂС…РЅРµРіРѕ Р±Р»РѕРєР°",
    nameEn: "Lat pulldown",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "vertical_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "EXISTING_APPROVED",
    plannedContentPackage: "EXISTING",
    legacyExerciseKey: "lat_pulldown",
  },
  {
    ordinal: 21,
    slug: "chair_sit_to_stand",
    familySlug: "bodyweight_squat",
    nameRu: "Р’СЃС‚Р°РІР°РЅРёРµ СЃРѕ СЃС‚СѓР»Р°",
    nameEn: "Chair sit-to-stand",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["CHAIR"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 22,
    slug: "wall_sit",
    familySlug: "bodyweight_squat",
    nameRu: "РџСЂРёСЃРµРґ Сѓ СЃС‚РµРЅС‹",
    nameEn: "Wall sit",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 23,
    slug: "box_squat_to_chair",
    familySlug: "bodyweight_squat",
    nameRu: "РџСЂРёСЃРµРґР°РЅРёРµ РЅР° СЃС‚СѓР»",
    nameEn: "Box squat to chair",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["CHAIR"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 24,
    slug: "dumbbell_romanian_deadlift",
    familySlug: "romanian_deadlift",
    nameRu: "Р СѓРјС‹РЅСЃРєР°СЏ С‚СЏРіР° СЃ РіР°РЅС‚РµР»СЏРјРё",
    nameEn: "Dumbbell Romanian deadlift",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "hinge",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 25,
    slug: "bodyweight_hip_thrust",
    familySlug: "hip_thrust",
    nameRu: "РЇРіРѕРґРёС‡РЅС‹Р№ С‚РѕР»С‡РѕРє СЃ РІРµСЃРѕРј С‚РµР»Р°",
    nameEn: "Bodyweight hip thrust",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["BENCH", "MAT"],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 26,
    slug: "barbell_hip_thrust",
    familySlug: "hip_thrust",
    nameRu: "РЇРіРѕРґРёС‡РЅС‹Р№ С‚РѕР»С‡РѕРє СЃРѕ С€С‚Р°РЅРіРѕР№",
    nameEn: "Barbell hip thrust",
    minLevel: "ADVANCED",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["BARBELL", "BENCH"],
    optionalEquipment: [],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 27,
    slug: "good_morning_bodyweight",
    familySlug: "romanian_deadlift",
    nameRu: "РќР°РєР»РѕРЅ В«РґРѕР±СЂРѕРµ СѓС‚СЂРѕВ» Р±РµР· РІРµСЃР°",
    nameEn: "Bodyweight good morning",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "hinge",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 28,
    slug: "supported_reverse_lunge",
    familySlug: "lunge_split",
    nameRu: "Р’С‹РїР°Рґ РЅР°Р·Р°Рґ СЃ РѕРїРѕСЂРѕР№",
    nameEn: "Supported reverse lunge",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["CHAIR"],
    movementPattern: "lunge",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: true,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 29,
    slug: "reverse_lunge",
    familySlug: "lunge_split",
    nameRu: "Р’С‹РїР°Рґ РЅР°Р·Р°Рґ",
    nameEn: "Reverse lunge",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "lunge",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: true,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 30,
    slug: "static_split_squat",
    familySlug: "lunge_split",
    nameRu: "РЎС‚Р°С‚РёС‡РµСЃРєРёР№ СЃРїР»РёС‚-РїСЂРёСЃРµРґ",
    nameEn: "Static split squat",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "lunge",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: true,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 31,
    slug: "low_step_up",
    familySlug: "step_up",
    nameRu: "РЁР°Рі РЅР° РЅРёР·РєСѓСЋ РїР»Р°С‚С„РѕСЂРјСѓ",
    nameEn: "Low step-up",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BENCH"],
    optionalEquipment: ["CHAIR"],
    movementPattern: "lunge",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: true,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 32,
    slug: "dumbbell_step_up",
    familySlug: "step_up",
    nameRu: "РЁР°Рі РЅР° РїР»Р°С‚С„РѕСЂРјСѓ СЃ РіР°РЅС‚РµР»СЏРјРё",
    nameEn: "Dumbbell step-up",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL", "BENCH"],
    optionalEquipment: [],
    movementPattern: "lunge",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: true,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 33,
    slug: "knee_push_ups",
    familySlug: "push_up",
    nameRu: "РћС‚Р¶РёРјР°РЅРёСЏ СЃ РєРѕР»РµРЅ",
    nameEn: "Knee push-ups",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 34,
    slug: "incline_push_ups",
    familySlug: "push_up",
    nameRu: "РћС‚Р¶РёРјР°РЅРёСЏ СЃ РѕРїРѕСЂРѕР№",
    nameEn: "Incline push-ups",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["BENCH", "CHAIR"],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 35,
    slug: "dumbbell_floor_press",
    familySlug: "dumbbell_press",
    nameRu: "Р–РёРј РіР°РЅС‚РµР»РµР№ Р»С‘Р¶Р° РЅР° РїРѕР»Сѓ",
    nameEn: "Dumbbell floor press",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: ["MAT"],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 36,
    slug: "barbell_bench_press",
    familySlug: "bench_press",
    nameRu: "Р–РёРј С€С‚Р°РЅРіРё Р»С‘Р¶Р°",
    nameEn: "Barbell bench press",
    minLevel: "ADVANCED",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["BARBELL", "BENCH"],
    optionalEquipment: [],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 37,
    slug: "dumbbell_shoulder_press",
    familySlug: "shoulder_press",
    nameRu: "Р–РёРј РіР°РЅС‚РµР»РµР№ СЃС‚РѕСЏ/СЃРёРґСЏ",
    nameEn: "Dumbbell shoulder press",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "vertical_push",
    primaryMuscleGroups: ["shoulders", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: true,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 38,
    slug: "seated_machine_shoulder_press",
    familySlug: "shoulder_press",
    nameRu: "Р–РёРј РїР»РµС‡ РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Seated machine shoulder press",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "vertical_push",
    primaryMuscleGroups: ["shoulders", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: true,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 39,
    slug: "band_overhead_press",
    familySlug: "shoulder_press",
    nameRu: "Р–РёРј СЌСЃРїР°РЅРґРµСЂР° РІРІРµСЂС…",
    nameEn: "Band overhead press",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "vertical_push",
    primaryMuscleGroups: ["shoulders", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: true,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 40,
    slug: "band_face_pull",
    familySlug: "band_pull_apart",
    nameRu: "РўСЏРіР° СЌСЃРїР°РЅРґРµСЂР° Рє Р»РёС†Сѓ",
    nameEn: "Band face pull",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["upper_back", "rear_delts"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 41,
    slug: "seated_cable_row",
    familySlug: "cable_row",
    nameRu: "РўСЏРіР° РЅРёР¶РЅРµРіРѕ Р±Р»РѕРєР° СЃРёРґСЏ",
    nameEn: "Seated cable row",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["CABLE"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 42,
    slug: "chest_supported_dumbbell_row",
    familySlug: "dumbbell_row",
    nameRu: "РўСЏРіР° РіР°РЅС‚РµР»РµР№ СЃ РѕРїРѕСЂРѕР№ РіСЂСѓРґРё",
    nameEn: "Chest-supported dumbbell row",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["DUMBBELL", "BENCH"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 43,
    slug: "barbell_bent_over_row",
    familySlug: "barbell_row",
    nameRu: "РўСЏРіР° С€С‚Р°РЅРіРё РІ РЅР°РєР»РѕРЅРµ",
    nameEn: "Barbell bent-over row",
    minLevel: "ADVANCED",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["BARBELL"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 44,
    slug: "assisted_pull_up_machine",
    familySlug: "lat_pulldown",
    nameRu: "РџРѕРґС‚СЏРіРёРІР°РЅРёСЏ РІ РіСЂР°РІРёС‚СЂРѕРЅРµ",
    nameEn: "Assisted pull-up machine",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "vertical_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 45,
    slug: "band_lat_pulldown",
    familySlug: "lat_pulldown",
    nameRu: "РўСЏРіР° СЌСЃРїР°РЅРґРµСЂР° СЃРІРµСЂС…Сѓ",
    nameEn: "Band lat pulldown",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "vertical_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: true,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 46,
    slug: "forearm_plank_knees",
    familySlug: "plank",
    nameRu: "РџР»Р°РЅРєР° РЅР° РїСЂРµРґРїР»РµС‡СЊСЏС… СЃ РєРѕР»РµРЅ",
    nameEn: "Forearm plank on knees",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "anti_extension_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 47,
    slug: "bird_dog",
    familySlug: "bird_dog",
    nameRu: "РџС‚РёС†Р°-СЃРѕР±Р°РєР°",
    nameEn: "Bird dog",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "anti_extension_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 48,
    slug: "side_plank_knee",
    familySlug: "side_plank",
    nameRu: "Р‘РѕРєРѕРІР°СЏ РїР»Р°РЅРєР° СЃ РѕРїРѕСЂРѕР№ РЅР° РєРѕР»РµРЅРѕ",
    nameEn: "Side plank on knee",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "lateral_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 49,
    slug: "side_plank",
    familySlug: "side_plank",
    nameRu: "Р‘РѕРєРѕРІР°СЏ РїР»Р°РЅРєР°",
    nameEn: "Side plank",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "lateral_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 50,
    slug: "pallof_press_band",
    familySlug: "anti_rotation",
    nameRu: "Р–РёРј РџР°Р»Р»РѕС„Р° СЃ СЌСЃРїР°РЅРґРµСЂРѕРј",
    nameEn: "Band Pallof press",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "anti_rotation_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 51,
    slug: "heel_taps",
    familySlug: "dead_bug",
    nameRu: "РљР°СЃР°РЅРёСЏ РїСЏС‚РѕРє Р»С‘Р¶Р°",
    nameEn: "Heel taps",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "anti_extension_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 52,
    slug: "dead_bug_hold",
    familySlug: "dead_bug",
    nameRu: "РЈРґРµСЂР¶Р°РЅРёРµ В«Р¶СѓРєР°В»",
    nameEn: "Dead bug hold",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "anti_extension_core",
    primaryMuscleGroups: ["core"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 53,
    slug: "side_lying_clamshell",
    familySlug: "hip_abduction",
    nameRu: "Р Р°РєСѓС€РєР° Р»С‘Р¶Р° РЅР° Р±РѕРєСѓ",
    nameEn: "Side-lying clamshell",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT", "RESISTANCE_BAND"],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 54,
    slug: "band_lateral_walk",
    familySlug: "hip_abduction",
    nameRu: "Р‘РѕРєРѕРІР°СЏ С…РѕРґСЊР±Р° СЃ СЌСЃРїР°РЅРґРµСЂРѕРј",
    nameEn: "Band lateral walk",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 55,
    slug: "glute_bridge_march",
    familySlug: "glute_bridge",
    nameRu: "РЇРіРѕРґРёС‡РЅС‹Р№ РјРѕСЃС‚ СЃ РјР°СЂС€РµРј",
    nameEn: "Glute bridge march",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: true,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 56,
    slug: "standing_calf_raise",
    familySlug: "calf_raise",
    nameRu: "РџРѕРґСЉС‘Рј РЅР° РЅРѕСЃРєРё СЃС‚РѕСЏ",
    nameEn: "Standing calf raise",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["DUMBBELL"],
    movementPattern: "calf",
    primaryMuscleGroups: ["calves"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 57,
    slug: "seated_calf_raise_machine",
    familySlug: "calf_raise",
    nameRu: "РџРѕРґСЉС‘Рј РЅР° РЅРѕСЃРєРё СЃРёРґСЏ РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Seated calf raise machine",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "calf",
    primaryMuscleGroups: ["calves"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 58,
    slug: "farmer_carry_dumbbell",
    familySlug: "farmer_carry",
    nameRu: "РџСЂРѕРіСѓР»РєР° С„РµСЂРјРµСЂР° СЃ РіР°РЅС‚РµР»СЏРјРё",
    nameEn: "Dumbbell farmer carry",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "carry",
    primaryMuscleGroups: ["grip", "core"],
    secondaryMuscleGroups: ["shoulders"],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 59,
    slug: "suitcase_carry_dumbbell",
    familySlug: "farmer_carry",
    nameRu: "РџРµСЂРµРЅРѕСЃ РіР°РЅС‚РµР»Рё РІ РѕРґРЅРѕР№ СЂСѓРєРµ",
    nameEn: "Dumbbell suitcase carry",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "carry",
    primaryMuscleGroups: ["core", "grip"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 60,
    slug: "brisk_outdoor_walk",
    familySlug: "outdoor_walk",
    nameRu: "Р‘С‹СЃС‚СЂР°СЏ РїСЂРѕРіСѓР»РєР°",
    nameEn: "Brisk outdoor walk",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["NONE"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "MODERATE",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 61,
    slug: "stationary_bike_easy",
    familySlug: "low_impact_cardio",
    nameRu: "Р’РµР»РѕС‚СЂРµРЅР°Р¶С‘СЂ РІ СЃРїРѕРєРѕР№РЅРѕРј С‚РµРјРїРµ",
    nameEn: "Easy stationary bike",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM", "HOME"],
    requiredEquipment: ["CARDIO_MACHINE"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 62,
    slug: "elliptical_easy",
    familySlug: "low_impact_cardio",
    nameRu: "Р­Р»Р»РёРїСЃРѕРёРґ РІ СЃРїРѕРєРѕР№РЅРѕРј С‚РµРјРїРµ",
    nameEn: "Easy elliptical",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["CARDIO_MACHINE"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 63,
    slug: "seated_march",
    familySlug: "low_impact_cardio",
    nameRu: "РњР°СЂС€ СЃРёРґСЏ",
    nameEn: "Seated march",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["CHAIR"],
    optionalEquipment: [],
    movementPattern: "low_impact_conditioning",
    primaryMuscleGroups: ["cardio", "hip_flexors"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 64,
    slug: "cat_cow_flow",
    familySlug: "mobility_flow",
    nameRu: "РљРѕС€РєР°-РєРѕСЂРѕРІР°",
    nameEn: "Cat-cow flow",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "mobility",
    primaryMuscleGroups: ["mobility"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 65,
    slug: "hip_flexor_stretch",
    familySlug: "gentle_stretch",
    nameRu: "Р Р°СЃС‚СЏР¶РєР° СЃРіРёР±Р°С‚РµР»РµР№ Р±РµРґСЂР°",
    nameEn: "Hip flexor stretch",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "mobility",
    primaryMuscleGroups: ["hip_flexors"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 66,
    slug: "thoracic_opener_open_book",
    familySlug: "gentle_stretch",
    nameRu: "Р Р°СЃРєСЂС‹С‚РёРµ РіСЂСѓРґРё В«РѕС‚РєСЂС‹С‚Р°СЏ РєРЅРёРіР°В»",
    nameEn: "Thoracic opener open book",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "mobility",
    primaryMuscleGroups: ["upper_back"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 67,
    slug: "diaphragmatic_breathing",
    familySlug: "recovery",
    nameRu: "Р”РёР°С„СЂР°РіРјР°Р»СЊРЅРѕРµ РґС‹С…Р°РЅРёРµ",
    nameEn: "Diaphragmatic breathing",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "recovery",
    primaryMuscleGroups: ["recovery"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 68,
    slug: "supine_knee_hugs",
    familySlug: "gentle_stretch",
    nameRu: "РџРѕРґС‚СЏРіРёРІР°РЅРёРµ РєРѕР»РµРЅРµР№ Р»С‘Р¶Р°",
    nameEn: "Supine knee hugs",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "recovery",
    primaryMuscleGroups: ["mobility"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 69,
    slug: "seated_leg_curl_machine",
    familySlug: "leg_curl",
    nameRu: "РЎРіРёР±Р°РЅРёРµ РЅРѕРі СЃРёРґСЏ",
    nameEn: "Seated leg curl machine",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "hinge",
    primaryMuscleGroups: ["hamstrings"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 70,
    slug: "leg_extension_machine",
    familySlug: "leg_press",
    nameRu: "Р Р°Р·РіРёР±Р°РЅРёРµ РЅРѕРі РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Leg extension machine",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 71,
    slug: "cable_chest_press",
    familySlug: "chest_press_machine",
    nameRu: "Р–РёРј РѕС‚ РіСЂСѓРґРё РЅР° Р±Р»РѕРєРµ",
    nameEn: "Cable chest press",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["CABLE"],
    optionalEquipment: [],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 72,
    slug: "pec_deck_machine",
    familySlug: "chest_press_machine",
    nameRu: "РЎРІРµРґРµРЅРёРµ СЂСѓРє РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Pec deck machine",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 73,
    slug: "lat_pulldown_neutral_grip",
    familySlug: "lat_pulldown",
    nameRu: "РўСЏРіР° РІРµСЂС…РЅРµРіРѕ Р±Р»РѕРєР° РЅРµР№С‚СЂР°Р»СЊРЅС‹Рј С…РІР°С‚РѕРј",
    nameEn: "Neutral-grip lat pulldown",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "vertical_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 74,
    slug: "band_squat",
    familySlug: "bodyweight_squat",
    nameRu: "РџСЂРёСЃРµРґР°РЅРёРµ СЃ СЌСЃРїР°РЅРґРµСЂРѕРј",
    nameEn: "Band squat",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "squat",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 75,
    slug: "band_glute_bridge",
    familySlug: "glute_bridge",
    nameRu: "РЇРіРѕРґРёС‡РЅС‹Р№ РјРѕСЃС‚ СЃ СЌСЃРїР°РЅРґРµСЂРѕРј",
    nameEn: "Band glute bridge",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: ["MAT"],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 76,
    slug: "band_chest_press",
    familySlug: "band_press",
    nameRu: "Р–РёРј СЌСЃРїР°РЅРґРµСЂР° РѕС‚ РіСЂСѓРґРё",
    nameEn: "Band chest press",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "horizontal_push",
    primaryMuscleGroups: ["chest", "triceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 77,
    slug: "dumbbell_goblet_split_squat",
    familySlug: "lunge_split",
    nameRu: "РЎРїР»РёС‚-РїСЂРёСЃРµРґ СЃ РіР°РЅС‚РµР»СЊСЋ Сѓ РіСЂСѓРґРё",
    nameEn: "Goblet split squat",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "lunge",
    primaryMuscleGroups: ["quads", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "MODERATE",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: true,
    singleLeg: true,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 78,
    slug: "dumbbell_lateral_raise",
    familySlug: "shoulder_press",
    nameRu: "Р Р°Р·РІРµРґРµРЅРёРµ РіР°РЅС‚РµР»РµР№ РІ СЃС‚РѕСЂРѕРЅС‹",
    nameEn: "Dumbbell lateral raise",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["DUMBBELL"],
    optionalEquipment: [],
    movementPattern: "vertical_push",
    primaryMuscleGroups: ["shoulders"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 79,
    slug: "machine_hip_abduction",
    familySlug: "hip_abduction",
    nameRu: "РћС‚РІРµРґРµРЅРёРµ Р±РµРґСЂР° РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Machine hip abduction",
    minLevel: "BEGINNER",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 80,
    slug: "back_extension_machine",
    familySlug: "romanian_deadlift",
    nameRu: "Р“РёРїРµСЂСЌРєСЃС‚РµРЅР·РёСЏ РІ С‚СЂРµРЅР°Р¶С‘СЂРµ",
    nameEn: "Back extension machine",
    minLevel: "INTERMEDIATE",
    supportedPlaces: ["GYM"],
    requiredEquipment: ["GYM_MACHINES"],
    optionalEquipment: [],
    movementPattern: "hinge",
    primaryMuscleGroups: ["erectors", "glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: false,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 81,
    slug: "standing_band_row",
    familySlug: "band_row",
    nameRu: "РўСЏРіР° СЌСЃРїР°РЅРґРµСЂР° СЃС‚РѕСЏ",
    nameEn: "Standing band row",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME"],
    requiredEquipment: ["RESISTANCE_BAND"],
    optionalEquipment: [],
    movementPattern: "horizontal_pull",
    primaryMuscleGroups: ["back", "biceps"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 82,
    slug: "mat_glute_bridge_hold",
    familySlug: "glute_bridge",
    nameRu: "РЈРґРµСЂР¶Р°РЅРёРµ СЏРіРѕРґРёС‡РЅРѕРіРѕ РјРѕСЃС‚Р°",
    nameEn: "Glute bridge hold",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: ["MAT"],
    movementPattern: "glute_isolation",
    primaryMuscleGroups: ["glutes"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: true,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 83,
    slug: "wall_angels",
    familySlug: "gentle_stretch",
    nameRu: "РђРЅРіРµР»С‹ Сѓ СЃС‚РµРЅС‹",
    nameEn: "Wall angels",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["BODYWEIGHT"],
    optionalEquipment: [],
    movementPattern: "mobility",
    primaryMuscleGroups: ["upper_back", "shoulders"],
    secondaryMuscleGroups: [],
    repetitionMode: "REPS_OR_DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
  {
    ordinal: 84,
    slug: "ankle_rocks",
    familySlug: "gentle_stretch",
    nameRu: "РџРѕРєР°С‡РёРІР°РЅРёСЏ РІ РіРѕР»РµРЅРѕСЃС‚РѕРїРµ",
    nameEn: "Ankle rocks",
    minLevel: "BEGINNER",
    supportedPlaces: ["HOME", "GYM"],
    requiredEquipment: ["NONE"],
    optionalEquipment: ["MAT"],
    movementPattern: "mobility",
    primaryMuscleGroups: ["ankles"],
    secondaryMuscleGroups: [],
    repetitionMode: "DURATION",
    impactLevel: "LOW",
    balanceRequirement: "LOW",
    floorRequired: false,
    overheadMovement: false,
    deepKneeFlexion: false,
    singleLeg: false,
    beginnerAllowed: true,
    initialCatalogStatus: "CANONICAL_01B",
    plannedContentPackage: "WORKOUT_CATALOG_01B",
    legacyExerciseKey: null,
  },
] satisfies readonly CatalogManifestEntry[];

export type WorkoutCatalogManifest = typeof WORKOUT_CATALOG_MANIFEST;
