/**
 * CATALOG-V3-01C-B — Batch B NEW content + Batch A pre-publish polish SoT.
 * Generated from WORKOUT-CATALOG-V3-SCOPE-01/04_TARGET_CATALOG_V3.csv (status=ADD).
 * Regenerator: node apps/api/scripts/generate-catalog-v3-01c-b-content.mjs
 * Do not invent UNKNOWN readiness / Energy / Timing / Media.
 */
import type { V3EquipmentGroupDraft, V3MuscleInvolvementDraft } from './catalog-v3-taxonomy';

export const CATALOG_V3_01C_B_VERSION = 'workout-catalog-v3-01c-b.1' as const;
export const CATALOG_V3_01C_B_CREATED_BY = 'system:catalog-v3-01c-b' as const;
export const CATALOG_V3_01C_B_ADVISORY_LOCK_KEY = 219_01_004;
export const CATALOG_V3_01C_B_EXPECTED_COUNT = 33 as const;
export const CATALOG_V3_01C_B_POLISH_EXPECTED_COUNT = 3 as const;
export const CATALOG_V3_01C_B_DEPRECATE_EXPECTED_COUNT = 1 as const;

export const V3_01C_B_DIFFICULTIES = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'] as const;
export type V301cBDifficulty = (typeof V3_01C_B_DIFFICULTIES)[number];

export type V301cBHeldEntry = {
  exerciseKey: string;
  reason: string;
};

export type V301cBContentEntry = {
  exerciseKey: string;
  nameRu: string;
  nameEn: string;
  familySlug: string;
  familyNameRu: string;
  familyNameEn: string;
  primaryMovementPattern: string;
  trainingRole: string;
  difficulty: V301cBDifficulty;
  progressionGroup: string;
  generatorMovementPattern: string;
  repetitionMode: 'REPS' | 'DURATION';
  supportedPlaces: readonly string[];
  muscles: readonly V3MuscleInvolvementDraft[];
  equipmentGroups: readonly V3EquipmentGroupDraft[];
  techniqueRu: string;
  commonMistakeRu: string;
  easierVariantRu: string;
  harderVariantRu: string;
  breathingRu: string;
  stopConditionsRu: string;
  defaultSets: number | null;
  defaultRepsMin: number | null;
  defaultRepsMax: number | null;
  defaultDurationSeconds: number | null;
  defaultRestSeconds: number;
  estimatedDurationSeconds: number;
  estimatedMinutes: number;
  riskLevel: string;
  beginnerAllowed: boolean;
};

/** Successor-revision polish for ever-APPROVED Batch A rows (immutable taxonomy). */
export type V301cBPolishEntry = {
  exerciseKey: string;
  polishReason: string;
  nameRu: string;
  nameEn: string;
  primaryMovementPattern: string;
  trainingRole: string;
  progressionGroup: string;
  supportedPlaces: readonly string[];
  muscles: readonly V3MuscleInvolvementDraft[];
  equipmentGroups: readonly V3EquipmentGroupDraft[];
};

export type V301cBDeprecationEntry = {
  exerciseKey: string;
  reason: string;
  mergeIntoKey: string;
};

export const CATALOG_V3_01C_B_HELD: readonly V301cBHeldEntry[] = [
  { exerciseKey: "front_squat_goblet_to_barbell", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: dual implement (DB/barbell) encoded as one key" },
  { exerciseKey: "leg_press_narrow", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: micro-variant of existing machine_leg_press" },
  { exerciseKey: "meadows_row", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: obscure specialty row; defer" },
  { exerciseKey: "hip_airplane", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: advanced niche balance drill" },
  { exerciseKey: "copenhagen_adductor_regression", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: specialized rehab-style progression" },
  { exerciseKey: "inverted_row", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: equipment OR uses BAR_RACK not in V3 vocab" },
  { exerciseKey: "y_raise_prone", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: LIGHT_DUMBBELL not in V3 equipment vocab" },
  { exerciseKey: "nordic_hamstring_regression", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: advanced niche; needs clearer regression identity" },
  { exerciseKey: "smith_squat", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: machine micro-variant of barbell squat family" },
  { exerciseKey: "landmine_press", reason: "BATCH_B_HELD_FOR_IDENTITY_REVIEW: landmine attachment missing from V3 equipment vocab (BARBELL alone insufficient)" },
  { exerciseKey: "machine_chest_fly", reason: "BATCH_B_HELD_DUPLICATE_OF_PUBLISHED: same pec-deck fly as pec_deck_machine; retain pec_deck_machine" },
  { exerciseKey: "glute_bridge_march_hold", reason: "BATCH_B_HELD_DUPLICATE_OF_PUBLISHED: same bridge+march as glute_bridge_march; retain glute_bridge_march" },
  { exerciseKey: "ankle_mobility_knee_over_toe", reason: "BATCH_B_HELD_DUPLICATE_OF_PUBLISHED: same knee-over-toe ankle rock as ankle_rocks; retain ankle_rocks" },
  { exerciseKey: "tibialis_raise", reason: "MISSING_ACCEPTED_ANKLE_DORSIFLEXION_PATTERN: KNEE_EXTENSION/CALF_RAISE are mechanically wrong; no accepted ankle dorsiflexion pattern without taxonomy expansion" }
];

export const CATALOG_V3_01C_B_DEPRECATIONS: readonly V301cBDeprecationEntry[] = [
  {
    exerciseKey: 'lat_pulldown_wide',
    reason:
      'NOT_JUSTIFIED_CANONICAL_IDENTITY: wide-grip machine pulldown is a grip micro-variant of published lat_pulldown (neutral-grip already separate as lat_pulldown_neutral_grip). HOME+LAT_PULLDOWN place/equipment inconsistency is closed by deprecation rather than inventing a duplicate identity.',
    mergeIntoKey: 'lat_pulldown',
  },
];

export const CATALOG_V3_01C_B_POLISH: readonly V301cBPolishEntry[] = [
  {
    exerciseKey: "bulgarian_split_squat",
    polishReason: "RFE Bulgarian split squat requires elevated support (BENCH), not BODYWEIGHT-only with OPTIONAL bench",
    nameRu: "Болгарский сплит-присед",
    nameEn: "Bulgarian split squat",
    primaryMovementPattern: "LUNGE",
    trainingRole: "MAIN",
    progressionGroup: "bulgarian",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0},{"equipmentCode":"BENCH","sortOrder":1}]},{"groupKind":"OPTIONAL","sortOrder":1,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
  },
  {
    exerciseKey: "chin_up",
    polishReason: "Add UPPER_BACK secondary — scapular retraction is mechanically involved",
    nameRu: "Подтягивания обратным хватом",
    nameEn: "Chin-up",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "MAIN",
    progressionGroup: "chin",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"LATS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"BICEPS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"PULL_UP_BAR","sortOrder":0}]}],
  },
  {
    exerciseKey: "dumbbell_fly",
    polishReason: "Add FRONT_DELTS secondary — shoulder flexion assists the fly arc",
    nameRu: "Разведения гантелей лёжа",
    nameEn: "Dumbbell fly",
    primaryMovementPattern: "HORIZONTAL_PUSH",
    trainingRole: "ISOLATION",
    progressionGroup: "dumbbell",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CHEST","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FRONT_DELTS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0},{"equipmentCode":"BENCH","sortOrder":1}]}],
  }
];

export const CATALOG_V3_01C_B_CONTENT: readonly V301cBContentEntry[] = [
  {
    exerciseKey: "jump_rope_easy",
    nameRu: "Прыжки на скакалке (лёгкие)",
    nameEn: "Easy jump rope",
    familySlug: "jump",
    familyNameRu: "Прыжки на скакалке (лёгкие)",
    familyNameEn: "Easy jump rope",
    primaryMovementPattern: "CONDITIONING",
    trainingRole: "CONDITIONING",
    difficulty: "INTERMEDIATE",
    progressionGroup: "jump",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"CALVES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"JUMP_ROPE","sortOrder":0}]}],
    techniqueRu: "Держите скакалку на уровне бёдер, локти у корпуса; прыгайте мягко на передней части стопы в спокойном темпе без высоких подскоков.",
    commonMistakeRu: "Прыгать слишком высоко и жёстко приземляться на прямые ноги.",
    easierVariantRu: "Делайте низкие подскоки без скакалки, имитируя вращение.",
    harderVariantRu: "Увеличьте темп, сохраняя низкий прыжок.",
    breathingRu: "Дышите ровно в ритме прыжков, не задерживая дыхание.",
    stopConditionsRu: "Остановитесь при боли в голеностопе, колене или одышке вне контроля.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "row_erg_easy",
    nameRu: "Гребля на тренажёре (лёгкая)",
    nameEn: "Easy rower",
    familySlug: "row",
    familyNameRu: "Гребля на тренажёре (лёгкая)",
    familyNameEn: "Easy rower",
    primaryMovementPattern: "CONDITIONING",
    trainingRole: "CONDITIONING",
    difficulty: "BEGINNER",
    progressionGroup: "row",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"QUADS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"ROW_ERG","sortOrder":0}]}],
    techniqueRu: "Сядьте на гребной тренажёр, стопы в упорах; отталкивайтесь ногами, затем включайте корпус и руки, возврат — руки, корпус, ноги.",
    commonMistakeRu: "Тянуть только руками и округлять поясницу в конце тяги.",
    easierVariantRu: "Снизьте сопротивление и укоротите амплитуду выезда.",
    harderVariantRu: "Добавьте чуть более длинный мощный толчок ногами.",
    breathingRu: "Выдох на тяге, вдох на возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице или резком дискомфорте в колене.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "stair_climber_easy",
    nameRu: "Степпер/лестница (лёгкая)",
    nameEn: "Easy stair climber",
    familySlug: "stair",
    familyNameRu: "Степпер/лестница (лёгкая)",
    familyNameEn: "Easy stair climber",
    primaryMovementPattern: "CONDITIONING",
    trainingRole: "CONDITIONING",
    difficulty: "BEGINNER",
    progressionGroup: "stair",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"QUADS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"STAIR_CLIMBER","sortOrder":0}]}],
    techniqueRu: "Встаньте на степпер, держитесь лёгким хватом за поручни; шагайте полной стопой в ровном темпе без давления всем весом на руки.",
    commonMistakeRu: "Переносить вес на поручни и семенить короткими шагами на носках.",
    easierVariantRu: "Уменьшите уровень сопротивления и темп.",
    harderVariantRu: "Увеличьте высоту/сопротивление, сохраняя опору корпуса.",
    breathingRu: "Дышите ровно, согласуя вдох-выдох с шагами.",
    stopConditionsRu: "Остановитесь при головокружении, боли в колене или острой одышке.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "battle_rope_alternating",
    nameRu: "Канаты (попеременные волны)",
    nameEn: "Battle ropes",
    familySlug: "battle",
    familyNameRu: "Канаты (попеременные волны)",
    familyNameEn: "Battle ropes",
    primaryMovementPattern: "CONDITIONING",
    trainingRole: "CONDITIONING",
    difficulty: "INTERMEDIATE",
    progressionGroup: "battle",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"SIDE_DELTS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BATTLE_ROPES","sortOrder":0}]}],
    techniqueRu: "Встаньте в полуприсед, канаты в руках; поочерёдно поднимайте и опускайте руки, создавая волны, корпус стабилен.",
    commonMistakeRu: "Раскачивать корпус и полностью разгибать локти рывком.",
    easierVariantRu: "Делайте волны меньшей амплитуды и короче по времени.",
    harderVariantRu: "Увеличьте амплитуду волн при том же контроле корпуса.",
    breathingRu: "Дышите коротко и регулярно, не задерживая дыхание.",
    stopConditionsRu: "Остановитесь при боли в плече, пояснице или потере контроля волн.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "sled_push_light",
    nameRu: "Толкание саней (лёгкое)",
    nameEn: "Light sled push",
    familySlug: "sled",
    familyNameRu: "Толкание саней (лёгкое)",
    familyNameEn: "Light sled push",
    primaryMovementPattern: "LOCOMOTION",
    trainingRole: "CONDITIONING",
    difficulty: "INTERMEDIATE",
    progressionGroup: "sled",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"QUADS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"SLED","sortOrder":0}]}],
    techniqueRu: "Наклонитесь к саням, руки на упорах, корпус жёсткий; толкайте короткими мощными шагами, сохраняя нейтральную спину.",
    commonMistakeRu: "Прогибать поясницу и «бегать» мелкими шагами без упора стопы.",
    easierVariantRu: "Снизьте нагрузку на санях и укоротите дистанцию.",
    harderVariantRu: "Увеличьте вес или длину отрезка при том же качестве шага.",
    breathingRu: "Выдыхайте на усилиях шага, не задерживайте дыхание надолго.",
    stopConditionsRu: "Остановитесь при боли в пояснице, колене или резкой потере опоры.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "high_knees_easy",
    nameRu: "Высокие колени (лёгкие)",
    nameEn: "Easy high knees",
    familySlug: "high",
    familyNameRu: "Высокие колени (лёгкие)",
    familyNameEn: "Easy high knees",
    primaryMovementPattern: "LOCOMOTION",
    trainingRole: "CONDITIONING",
    difficulty: "INTERMEDIATE",
    progressionGroup: "high",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HIP_FLEXORS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Бегите на месте, поднимая колени примерно к уровню бедра в контролируемом темпе, приземляясь мягко на переднюю часть стопы.",
    commonMistakeRu: "Заваливать корпус назад и шлёпать пятками.",
    easierVariantRu: "Маршируйте с высоким коленом без фазы полёта.",
    harderVariantRu: "Ускорьте каденс, сохраняя высоту колена.",
    breathingRu: "Дышите ритмично в темпе шагов.",
    stopConditionsRu: "Остановитесь при боли в колене, голени или головокружении.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "march_in_place",
    nameRu: "Марш на месте",
    nameEn: "March in place",
    familySlug: "march",
    familyNameRu: "Марш на месте",
    familyNameEn: "March in place",
    primaryMovementPattern: "LOCOMOTION",
    trainingRole: "WARMUP",
    difficulty: "BEGINNER",
    progressionGroup: "march",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"CONDITIONING_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HIP_FLEXORS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Стоя прямо, поочерёдно поднимайте колени до комфортной высоты, сохраняя лёгкую осанку и мягкую постановку стопы.",
    commonMistakeRu: "Сутулиться и раскачивать таз из стороны в сторону.",
    easierVariantRu: "Уменьшите высоту подъёма колена.",
    harderVariantRu: "Добавьте лёгкое движение руками в противофазе.",
    breathingRu: "Дышите спокойно и ровно.",
    stopConditionsRu: "Остановитесь при боли в суставе или головокружении.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "shoulder_caress_circles",
    nameRu: "Круги руками/плечами",
    nameEn: "Arm circles",
    familySlug: "shoulder",
    familyNameRu: "Круги руками/плечами",
    familyNameEn: "Arm circles",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "WARMUP",
    difficulty: "BEGINNER",
    progressionGroup: "shoulder",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"SIDE_DELTS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Встаньте свободно, руки вдоль тела; выполняйте медленные круги плечами назад, затем вперёд, без боли и без рывков.",
    commonMistakeRu: "Делать круги слишком быстро и поднимать плечи к ушам.",
    easierVariantRu: "Уменьшите амплитуду кругов.",
    harderVariantRu: "Увеличьте амплитуду, сохраняя контроль лопаток.",
    breathingRu: "Вдох при расширении груди, выдох при расслаблении плеч.",
    stopConditionsRu: "Остановитесь при острой боли или щелчке с болью в плече.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "world_greatest_stretch",
    nameRu: "World’s greatest stretch",
    nameEn: "World greatest stretch",
    familySlug: "world",
    familyNameRu: "World’s greatest stretch",
    familyNameEn: "World greatest stretch",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "MOBILITY",
    difficulty: "BEGINNER",
    progressionGroup: "world",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HIP_FLEXORS","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Из упора выведите одну ногу в выпад, опустите таз, поверните корпус к передней ноге и при необходимости вытяните руку вверх, затем смените сторону.",
    commonMistakeRu: "Проваливать поясницу и ронять заднее колено без контроля.",
    easierVariantRu: "Сократите глубину выпада и амплитуду поворота.",
    harderVariantRu: "Увеличьте время фиксации в конечной позиции.",
    breathingRu: "Дышите глубоко, удлиняя выдох в растяжении.",
    stopConditionsRu: "Остановитесь при боли в колене, паху или пояснице.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "90_90_hip_switch",
    nameRu: "Переходы 90/90",
    nameEn: "90/90 hip switch",
    familySlug: "90",
    familyNameRu: "Переходы 90/90",
    familyNameEn: "90/90 hip switch",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "MOBILITY",
    difficulty: "BEGINNER",
    progressionGroup: "90",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"HIP_FLEXORS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Сядьте в позицию 90/90 (оба колена согнуты ~90°); сохраняя корпус высоким, переведите голени через центр в зеркальную 90/90.",
    commonMistakeRu: "Заваливать корпус назад и помогать руками чрезмерно.",
    easierVariantRu: "Используйте руки для лёгкой поддержки сзади.",
    harderVariantRu: "Выполняйте переходы без опоры руками.",
    breathingRu: "Выдох на переходе, вдох в стабильной позе.",
    stopConditionsRu: "Остановитесь при боли в колене или остром дискомфорте в бедре.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "thread_the_needle",
    nameRu: "Игла (thoracic)",
    nameEn: "Thread the needle",
    familySlug: "thread",
    familyNameRu: "Игла (thoracic)",
    familyNameEn: "Thread the needle",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "MOBILITY",
    difficulty: "BEGINNER",
    progressionGroup: "thread",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"UPPER_BACK","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Встаньте на четвереньки; проведите одну руку под корпусом ладонью вверх, опуская плечо к полу, затем вернитесь и раскройте грудной отдел.",
    commonMistakeRu: "Крутить только шеей вместо грудного отдела.",
    easierVariantRu: "Уменьшите амплитуду прохода руки под корпусом.",
    harderVariantRu: "Задержитесь 2–3 секунды в конечной ротации.",
    breathingRu: "Выдох при ротации, вдох при возврате.",
    stopConditionsRu: "Остановитесь при боли в шее, плече или пояснице.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "couch_stretch",
    nameRu: "Растяжка сгибателей бедра у опоры",
    nameEn: "Couch stretch",
    familySlug: "couch",
    familyNameRu: "Растяжка сгибателей бедра у опоры",
    familyNameEn: "Couch stretch",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "MOBILITY",
    difficulty: "BEGINNER",
    progressionGroup: "couch",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"HIP_FLEXORS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Заднее колено у опоры/дивана, стопа вверх по опоре; передняя нога в выпаде, таз подан вперёд, корпус высокий без боли в пояснице.",
    commonMistakeRu: "Сильно прогибать поясницу вместо наклона таза.",
    easierVariantRu: "Отойдите тазом дальше от опоры, снизив интенсивность.",
    harderVariantRu: "Подтяните таз ближе к опоре при нейтральной пояснице.",
    breathingRu: "Длинный выдох в растяжении сгибателей бедра.",
    stopConditionsRu: "Остановитесь при острой боли в колене или пояснице.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "neck_mobility_gentle",
    nameRu: "Мягкая мобильность шеи",
    nameEn: "Gentle neck mobility",
    familySlug: "neck",
    familyNameRu: "Мягкая мобильность шеи",
    familyNameEn: "Gentle neck mobility",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "MOBILITY",
    difficulty: "BEGINNER",
    progressionGroup: "neck",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Сидя или стоя с ровной осанкой, медленно выполняйте безопасные движения шеи: наклоны и повороты в комфортном диапазоне без рывков.",
    commonMistakeRu: "Делать круговые рывки и уходить в боль.",
    easierVariantRu: "Уменьшите амплитуду до едва заметного движения.",
    harderVariantRu: "Удерживайте конечную позицию 2 секунды при полном контроле.",
    breathingRu: "Дышите спокойно, не задерживая дыхание.",
    stopConditionsRu: "Остановитесь при головокружении, онемении или острой боли.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "child_pose",
    nameRu: "Поза ребёнка",
    nameEn: "Child's pose",
    familySlug: "child",
    familyNameRu: "Поза ребёнка",
    familyNameEn: "Child's pose",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "RECOVERY",
    difficulty: "BEGINNER",
    progressionGroup: "child",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"MOBILITY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"LOWER_BACK","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Сядьте на пятки, наклонитесь вперёд, руки протяните вперёд или вдоль тела; расслабьте грудной отдел и дышите в пол.",
    commonMistakeRu: "Сильно давить плечами в пол через боль.",
    easierVariantRu: "Поставьте подушку между бёдрами и голенями.",
    harderVariantRu: "Удлините время удержания при комфорте.",
    breathingRu: "Медленный вдох в рёбра, длинный выдох в расслабление.",
    stopConditionsRu: "Остановитесь при боли в коленях или остром дискомфорте в плече.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "foam_roll_quads",
    nameRu: "МФР квадрицепсов",
    nameEn: "Foam roll quads",
    familySlug: "foam",
    familyNameRu: "МФР квадрицепсов",
    familyNameEn: "Foam roll quads",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "RECOVERY",
    difficulty: "BEGINNER",
    progressionGroup: "foam",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"RECOVERY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"QUADS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"FOAM_ROLLER","sortOrder":0}]}],
    techniqueRu: "Лягте животом на ролик под бёдрами; медленно прокатывайте квадрицепсы, останавливаясь на напряжённых участках без резкой боли.",
    commonMistakeRu: "Катиться слишком быстро и задерживать дыхание.",
    easierVariantRu: "Снизьте давление, опираясь больше на руки.",
    harderVariantRu: "Увеличьте время паузы на триггерных зонах.",
    breathingRu: "Дышите ровно; на плотных участках удлиняйте выдох.",
    stopConditionsRu: "Остановитесь при острой боли, онемении или синяковой боли.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "box_breathing",
    nameRu: "Квадратное дыхание",
    nameEn: "Box breathing",
    familySlug: "box",
    familyNameRu: "Квадратное дыхание",
    familyNameEn: "Box breathing",
    primaryMovementPattern: "MOBILITY",
    trainingRole: "RECOVERY",
    difficulty: "BEGINNER",
    progressionGroup: "box",
    generatorMovementPattern: "mobility",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"RECOVERY_SYSTEMIC","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Сидя удобно, выполните цикл: вдох 4 счёта, пауза 4, выдох 4, пауза 4; плечи расслаблены, живот мягко участвует.",
    commonMistakeRu: "Набирать воздух только верхом груди и ускорять счёт.",
    easierVariantRu: "Сократите фазы до 3 счётов.",
    harderVariantRu: "Удлините фазы до 5–6 счётов при сохранении спокойствия.",
    breathingRu: "Равномерные фазы без форсирования.",
    stopConditionsRu: "Остановитесь при головокружении или тревожном дискомфорте.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "hip_adduction_machine",
    nameRu: "Сведения ног в тренажёре",
    nameEn: "Hip adduction machine",
    familySlug: "hip",
    familyNameRu: "Сведения ног в тренажёре",
    familyNameEn: "Hip adduction machine",
    primaryMovementPattern: "HIP_ADDUCTION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "hip",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"ADDUCTORS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"HIP_ADDUCTION_MACHINE","sortOrder":0}]}],
    techniqueRu: "Сядьте в тренажёр сведения, подушки снаружи бёдер; сведите ноги к центру под контролем и медленно верните.",
    commonMistakeRu: "Рывком сводить ноги и помогать корпусом.",
    easierVariantRu: "Уменьшите вес и амплитуду.",
    harderVariantRu: "Пауза 1 секунда в сведённом положении.",
    breathingRu: "Выдох при сведении, вдох при возврате.",
    stopConditionsRu: "Остановитесь при боли в паху или колене.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "donkey_calf_raise",
    nameRu: "Подъёмы на носки «осликом»/в тренажёре",
    nameEn: "Donkey/machine calf raise",
    familySlug: "donkey",
    familyNameRu: "Подъёмы на носки «осликом»/в тренажёре",
    familyNameEn: "Donkey/machine calf raise",
    primaryMovementPattern: "CALF_RAISE",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "donkey",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"CALVES","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ANY_OF","sortOrder":0,"items":[{"equipmentCode":"CALF_MACHINE","sortOrder":0},{"equipmentCode":"BODYWEIGHT","sortOrder":1}]}],
    techniqueRu: "В тренажёре или с опорой наклонитесь, колени мягкие; поднимитесь на носки максимальной амплитудой и опуститесь с контролем.",
    commonMistakeRu: "Сгибать колени в такт и делать короткую амплитуду.",
    easierVariantRu: "Выполняйте с собственным весом у опоры.",
    harderVariantRu: "Добавьте паузу наверху на носках.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в ахилле или голеностопе.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "dead_bug_band",
    nameRu: "Dead bug с лентой",
    nameEn: "Banded dead bug",
    familySlug: "dead",
    familyNameRu: "Dead bug с лентой",
    familyNameEn: "Banded dead bug",
    primaryMovementPattern: "CORE_ANTI_EXTENSION",
    trainingRole: "ACCESSORY",
    difficulty: "BEGINNER",
    progressionGroup: "dead",
    generatorMovementPattern: "core",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"DEEP_CORE","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"RESISTANCE_BAND","sortOrder":0},{"equipmentCode":"MAT","sortOrder":1}]}],
    techniqueRu: "Лёжа на спине, лента в руках над грудью; сохраняя поясницу прижатой, поочерёдно выпрямляйте противоположные руку и ногу.",
    commonMistakeRu: "Отрывать поясницу от пола и задерживать дыхание.",
    easierVariantRu: "Упростите до движения только ногами.",
    harderVariantRu: "Замедлите фазу разгибания до 3 секунд.",
    breathingRu: "Выдох при разгибании конечности, вдох при возврате.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "russian_twist_bodyweight",
    nameRu: "Русские скручивания",
    nameEn: "Russian twist",
    familySlug: "russian",
    familyNameRu: "Русские скручивания",
    familyNameEn: "Russian twist",
    primaryMovementPattern: "CORE_ROTATION",
    trainingRole: "ACCESSORY",
    difficulty: "BEGINNER",
    progressionGroup: "russian",
    generatorMovementPattern: "core",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"OBLIQUES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"ABS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0},{"equipmentCode":"MAT","sortOrder":1}]}],
    techniqueRu: "Сядьте, корпус отклонён назад, стопы на полу или слегка подняты; поворачивайте корпус из стороны в сторону без рывков.",
    commonMistakeRu: "Крутить только руками при неподвижном корпусе.",
    easierVariantRu: "Держите стопы на полу и уменьшите амплитуду.",
    harderVariantRu: "Поднимите стопы и замедлите повороты.",
    breathingRu: "Выдох на каждом повороте.",
    stopConditionsRu: "Остановитесь при боли в пояснице или шее.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "hollow_body_hold",
    nameRu: "Hollow body hold",
    nameEn: "Hollow hold",
    familySlug: "hollow",
    familyNameRu: "Hollow body hold",
    familyNameEn: "Hollow hold",
    primaryMovementPattern: "CORE_ANTI_EXTENSION",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "hollow",
    generatorMovementPattern: "core",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"ABS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"DEEP_CORE","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"MAT","sortOrder":0}]}],
    techniqueRu: "Лёжа на спине, прижмите поясницу к полу; оторвите лопатки и ноги, руки вдоль ушей или вперёд, удерживайте форму «лодочки».",
    commonMistakeRu: "Прогибать поясницу и задерживать дыхание.",
    easierVariantRu: "Согните колени и удерживайте короче.",
    harderVariantRu: "Выпрямите ноги ниже к полу без потери контакта поясницы.",
    breathingRu: "Дышите коротко и ровно, сохраняя напряжение кора.",
    stopConditionsRu: "Остановитесь при боли в пояснице или шее.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "band_good_morning",
    nameRu: "Good morning с лентой",
    nameEn: "Band good morning",
    familySlug: "band",
    familyNameRu: "Good morning с лентой",
    familyNameEn: "Band good morning",
    primaryMovementPattern: "HINGE",
    trainingRole: "ACCESSORY",
    difficulty: "BEGINNER",
    progressionGroup: "band",
    generatorMovementPattern: "hinge",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"HAMSTRINGS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"LOWER_BACK","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"RESISTANCE_BAND","sortOrder":0}]}],
    techniqueRu: "Ленту на плечах/в руках с опорой под стопами; с мягкими коленями наклонитесь тазом назад до натяжения задней цепи и вернитесь.",
    commonMistakeRu: "Округлять спину и сгибать только в пояснице.",
    easierVariantRu: "Укоротите амплитуду наклона.",
    harderVariantRu: "Замедлите негатив до 3 секунд.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "scapular_retraction_hang",
    nameRu: "Лопаточные подтягивания в висе",
    nameEn: "Scapular pull-up hang",
    familySlug: "scapular",
    familyNameRu: "Лопаточные подтягивания в висе",
    familyNameEn: "Scapular pull-up hang",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "scapular",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"UPPER_BACK","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"LATS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"PULL_UP_BAR","sortOrder":0}]}],
    techniqueRu: "Повисните на перекладине пассивным хватом; не сгибая локти, опустите и сведите лопатки, подняв корпус на миллиметры, затем отпустите в пассивный вис.",
    commonMistakeRu: "Сгибать руки в локтях как в подтягивании.",
    easierVariantRu: "Держите одну ногу на опоре для разгрузки.",
    harderVariantRu: "Увеличьте паузу в активном висе.",
    breathingRu: "Выдох при сведении лопаток, вдох в пассиве.",
    stopConditionsRu: "Остановитесь при боли в плече или локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "suitcase_carry_kettlebell",
    nameRu: "Прогулка с гирей в одной руке",
    nameEn: "KB suitcase carry",
    familySlug: "suitcase",
    familyNameRu: "Прогулка с гирей в одной руке",
    familyNameEn: "KB suitcase carry",
    primaryMovementPattern: "CARRY",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "suitcase",
    generatorMovementPattern: "cardio",
    repetitionMode: "DURATION",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"OBLIQUES","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FOREARMS_GRIP","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"KETTLEBELL","sortOrder":0}]}],
    techniqueRu: "Возьмите гирю в одну руку сбоку; идите ровно, не заваливаясь в сторону нагрузки, плечи горизонтальны, корпус жёсткий.",
    commonMistakeRu: "Наклоняться к гире и сутулиться.",
    easierVariantRu: "Уменьшите вес и дистанцию.",
    harderVariantRu: "Увеличьте вес или длину прохода.",
    breathingRu: "Дышите ровно, сохраняя напряжение боковой стенки.",
    stopConditionsRu: "Остановитесь при боли в пояснице или потере хвата.",
    defaultSets: null,
    defaultRepsMin: null,
    defaultRepsMax: null,
    defaultDurationSeconds: 40,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 240,
    estimatedMinutes: 5,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "box_step_down",
    nameRu: "Сходы с тумбы",
    nameEn: "Box step-down",
    familySlug: "box",
    familyNameRu: "Сходы с тумбы",
    familyNameEn: "Box step-down",
    primaryMovementPattern: "LUNGE",
    trainingRole: "ACCESSORY",
    difficulty: "BEGINNER",
    progressionGroup: "box",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BOX_STEP","sortOrder":0}]}],
    techniqueRu: "Встаньте на тумбу; медленно шагайте одной ногой вниз, контролируя сгибание опорного колена, затем вернитесь на тумбу.",
    commonMistakeRu: "Падать вниз без контроля и заваливать колено внутрь.",
    easierVariantRu: "Используйте более низкую тумбу.",
    harderVariantRu: "Замедлите спуск до 3–4 секунд.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в колене.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "hack_squat_machine",
    nameRu: "Гакк-приседания",
    nameEn: "Hack squat",
    familySlug: "hack",
    familyNameRu: "Гакк-приседания",
    familyNameEn: "Hack squat",
    primaryMovementPattern: "SQUAT",
    trainingRole: "MAIN",
    difficulty: "INTERMEDIATE",
    progressionGroup: "hack",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"HACK_SQUAT","sortOrder":0}]}],
    techniqueRu: "Встаньте в гакк-тренажёр, спина к подушке, стопы на платформе; опуститесь в присед и выжмите платформу, не отрывая поясницу.",
    commonMistakeRu: "Отрывать таз от подушки и сводить колени внутрь.",
    easierVariantRu: "Уменьшите глубину и вес.",
    harderVariantRu: "Пауза внизу 1 секунда.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в колене или пояснице.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "lateral_lunge",
    nameRu: "Боковые выпады",
    nameEn: "Lateral lunge",
    familySlug: "lateral",
    familyNameRu: "Боковые выпады",
    familyNameEn: "Lateral lunge",
    primaryMovementPattern: "LUNGE",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "lateral",
    generatorMovementPattern: "squat",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"QUADS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"GLUTES","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"ADDUCTORS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BODYWEIGHT","sortOrder":0}]}],
    techniqueRu: "Из стойки шагните в сторону, сгибайте рабочую ногу, таз назад, вторая нога прямая; оттолкнитесь и вернитесь в центр.",
    commonMistakeRu: "Заваливать колено внутрь и округлять спину.",
    easierVariantRu: "Укоротите шаг и глубину.",
    harderVariantRu: "Замедлите опускание и добавьте паузу.",
    breathingRu: "Вдох в сторону, выдох при возврате.",
    stopConditionsRu: "Остановитесь при боли в колене или паху.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "shrug_dumbbell",
    nameRu: "Шраги с гантелями",
    nameEn: "Dumbbell shrug",
    familySlug: "shrug",
    familyNameRu: "Шраги с гантелями",
    familyNameEn: "Dumbbell shrug",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "shrug",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"TRAPS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Стоя с гантелями по бокам, поднимите плечи строго вверх к ушам без вращения и медленно опустите.",
    commonMistakeRu: "Крутить плечами и помогать руками сгибая локти.",
    easierVariantRu: "Уменьшите вес.",
    harderVariantRu: "Пауза 1–2 секунды наверху.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в шее или плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "front_raise_dumbbell",
    nameRu: "Подъёмы гантелей перед собой",
    nameEn: "Front raise",
    familySlug: "front",
    familyNameRu: "Подъёмы гантелей перед собой",
    familyNameEn: "Front raise",
    primaryMovementPattern: "VERTICAL_PUSH",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "front",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"FRONT_DELTS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Стоя, гантели перед бёдрами; поднимите руки перед собой до уровня плеч слегка согнутыми локтями и опустите под контролем.",
    commonMistakeRu: "Раскачивать корпус и поднимать выше комфорта с рывком.",
    easierVariantRu: "Поднимайте по одной руке с меньшим весом.",
    harderVariantRu: "Замедлите опускание до 3 секунд.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в передней части плеча.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "cable_bicep_curl",
    nameRu: "Сгибания на бицепс в кроссовере",
    nameEn: "Cable biceps curl",
    familySlug: "cable",
    familyNameRu: "Сгибания на бицепс в кроссовере",
    familyNameEn: "Cable biceps curl",
    primaryMovementPattern: "ELBOW_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "BEGINNER",
    progressionGroup: "cable",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["GYM"],
    muscles: [{"muscleCode":"BICEPS","involvement":"PRIMARY","sortOrder":0}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"CABLE","sortOrder":0}]}],
    techniqueRu: "Встаньте у нижнего блока, локти у корпуса; сгибайте руки к плечам и медленно разгибайте, не раскачиваясь.",
    commonMistakeRu: "Помогать корпусом и уводить локти вперёд.",
    easierVariantRu: "Уменьшите вес.",
    harderVariantRu: "Пауза вверху 1 секунда.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в локте.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: true,
  },
  {
    exerciseKey: "ez_bar_curl",
    nameRu: "Сгибания на EZ-грифе",
    nameEn: "EZ-bar curl",
    familySlug: "ez",
    familyNameRu: "Сгибания на EZ-грифе",
    familyNameEn: "EZ-bar curl",
    primaryMovementPattern: "ELBOW_FLEXION",
    trainingRole: "ISOLATION",
    difficulty: "INTERMEDIATE",
    progressionGroup: "ez",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"BICEPS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"FOREARMS_GRIP","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"EZ_BAR","sortOrder":0}]}],
    techniqueRu: "Возьмите EZ-гриф хватом по изгибам; сгибайте локти к плечам, удерживая локти у корпуса, и контролируемо опустите.",
    commonMistakeRu: "Раскачиваться и разводить локти в стороны.",
    easierVariantRu: "Уменьшите вес и амплитуду.",
    harderVariantRu: "Медленный негатив 3 секунды.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли в локте или запястье.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "bench_dip",
    nameRu: "Отжимания от скамьи на трицепс",
    nameEn: "Bench dip",
    familySlug: "bench",
    familyNameRu: "Отжимания от скамьи на трицепс",
    familyNameEn: "Bench dip",
    primaryMovementPattern: "VERTICAL_PUSH",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "bench",
    generatorMovementPattern: "push",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"TRICEPS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"CHEST","involvement":"SECONDARY","sortOrder":1},{"muscleCode":"FRONT_DELTS","involvement":"SECONDARY","sortOrder":2}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"BENCH","sortOrder":0}]}],
    techniqueRu: "Оперевшись руками о скамью сзади, ноги вперед; согните локти и опустите таз, затем выжмите себя вверх, плечи стабильны.",
    commonMistakeRu: "Опускаться слишком глубоко с провалом плеч вперёд.",
    easierVariantRu: "Согните ноги и уменьшите глубину.",
    harderVariantRu: "Выпрямите ноги дальше от скамьи.",
    breathingRu: "Вдох вниз, выдох вверх.",
    stopConditionsRu: "Остановитесь при боли в передней части плеча.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  },
  {
    exerciseKey: "upright_row_dumbbell",
    nameRu: "Тяга гантелей к подбородку",
    nameEn: "Dumbbell upright row",
    familySlug: "upright",
    familyNameRu: "Тяга гантелей к подбородку",
    familyNameEn: "Dumbbell upright row",
    primaryMovementPattern: "VERTICAL_PULL",
    trainingRole: "ACCESSORY",
    difficulty: "INTERMEDIATE",
    progressionGroup: "upright",
    generatorMovementPattern: "pull",
    repetitionMode: "REPS",
    supportedPlaces: ["HOME","GYM"],
    muscles: [{"muscleCode":"SIDE_DELTS","involvement":"PRIMARY","sortOrder":0},{"muscleCode":"TRAPS","involvement":"SECONDARY","sortOrder":1}],
    equipmentGroups: [{"groupKind":"ALL_OF","sortOrder":0,"items":[{"equipmentCode":"DUMBBELL","sortOrder":0}]}],
    techniqueRu: "Стоя, гантели перед бёдрами; тяните их вверх вдоль корпуса до уровня нижней части груди, локти выше кистей, без рывка.",
    commonMistakeRu: "Поднимать выше плеч и зажимать шею.",
    easierVariantRu: "Укоротите амплитуду до комфортной высоты.",
    harderVariantRu: "Замедлите негатив.",
    breathingRu: "Выдох вверх, вдох вниз.",
    stopConditionsRu: "Остановитесь при боли или защемлении в плече.",
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultDurationSeconds: null,
    defaultRestSeconds: 60,
    estimatedDurationSeconds: 180,
    estimatedMinutes: 4,
    riskLevel: 'low',
    beginnerAllowed: false,
  }
];
