CREATE TABLE IF NOT EXISTS "UserSubscription" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL UNIQUE REFERENCES "User"(id) ON DELETE CASCADE,
  tier TEXT NOT NULL CHECK (tier IN ('FREE', 'PREMIUM')),
  status TEXT NOT NULL DEFAULT 'active',
  "startsAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expiresAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "UserSubscription_userId_idx" ON "UserSubscription" ("userId");

ALTER TABLE "AuthIdentity" ADD COLUMN IF NOT EXISTS "credentialHash" TEXT;

CREATE TABLE IF NOT EXISTS "AnonymousMigration" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "anonymousUserId" UUID NOT NULL UNIQUE,
  "targetUserId" UUID NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  "migratedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
