ALTER TABLE "AIUsageLog" ADD COLUMN IF NOT EXISTS "tier" TEXT;
ALTER TABLE "AIUsageLog" ADD COLUMN IF NOT EXISTS "thinkingEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AIUsageLog" ADD COLUMN IF NOT EXISTS "totalTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AIUsageLog" ADD COLUMN IF NOT EXISTS "estimatedCost" DECIMAL(12, 6) NOT NULL DEFAULT 0;
ALTER TABLE "AIUsageLog" ADD COLUMN IF NOT EXISTS "latencyMs" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AIUsageLog" ADD COLUMN IF NOT EXISTS "success" BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS "AIUsageLog_userId_success_createdAt_idx"
  ON "AIUsageLog" ("userId", "success", "createdAt");
