ALTER TABLE "ShoppingItem" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ShoppingItem" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'other';
ALTER TABLE "ShoppingItem" ADD COLUMN IF NOT EXISTS "purchased" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ShoppingItem" ADD COLUMN IF NOT EXISTS "estimatedUnitPrice" DECIMAL(10,2);
ALTER TABLE "ShoppingItem" ADD COLUMN IF NOT EXISTS "estimatedCost" DECIMAL(10,2);
ALTER TABLE "ShoppingItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS "Product_canonicalName_key" ON "Product"("canonicalName");
